### ISSUE TITLE
Scrollwheel scrolls thru tabs

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#281]
As well as the key shortcuts it would be great to use the mousewheel to scroll thru tabs.

**Comment by wvelez6** [comment]
Hey Matt, under chrome and safari on OS x the tabs switch on their own very fast when used with a logitech "smooth scrolling". When Im working on a code it switches to the other file without me touching the mouse. I opened the console on bot chrome and safari and it gives this error: Uncaught TypeError: Cannot read property 'hasFocus' of undefinedonmousewheel @ (index):2. It works fine under firefox.

**Comment by mattpass** [comment]
OK thanks for letting me know. Reopened issue so I can look into it.

**Comment by wvelez6** [comment]
Attached its a screenshot of Safari debugger. Hope it helps you.
![safari_debugger](https://cloud.githubusercontent.com/assets/7291247/13221865/729a01b8-d94b-11e5-951c-7626b465e22e.png)

**Comment by mattpass** [comment]
Whilst I can't reproduce these exact circumstances as I don't have that mouse or feature, I can reproduce the same error by trying to scroll tabs when none are open. Added a fix for this and hope it fixes your issue too. Closing.
