### ISSUE TITLE
Became unresponsive to Save and Open file.

### ISSUE THREAD

**Issue by MrData1** [mattpass/ICEcoder#356]
Love the coder. Everything worked fine for a week, now after editing any file it doesn't save. Clicking save or CTRL+S just shows on bottom of navigator "saving" and hangs there. Trying to open any file after this and it just says "opening" but doesn't open.  Tried clearing cookies, tried different browsers, different computers. Issue still persists. Deleted ICEcoder and re-installed but still issue persists.  If it helps the error-log.txt is full of these errors

[07-Feb-2014 18:01:55 America/Chicago] PHP Warning:  strpos() [<a href='function.strpos'>function.strpos</a>]: Empty needle in /home/webny/public_html/ICEcoder-master/lib/get-branch.php on line 24

**Comment by ecos** [comment]
Waow, same error message 403 (Forbidden) /lib/file-control-xhr.php and symptom (stopped being able to save a file after a while), same hosting provider Greengeeks. 
For me it happened on a PHP file and the trigger was an SQL query within.
This line to be precise (haven't narrowed it down to the guilty sequence of characters) :
`SELECT *, GROUP_CONCAT(DISTINCT weekday.id ORDER BY weekday.id ASC) as weekdays`
I bet you it is a deep packet inspection firewall issue and nothing to do with ICECoder.
And I agree they seem to suck.
Cheers

**Comment by mattpass** [comment]
@ecos Is very strange and no reason why ICEcoder would deny you saving that. Does sound like it is Greengeeks denying it due to SQL injections, overflow: hidden etc, that's pretty bad of them - shouldn't be scanning anything I say!

Will see if I can write some extra code so on error 4xx etc it at least allows you to continue, but can't help much with them blocking things.

**Comment by webguide** [comment]
Same problem as in the issue subject:
Became unresponsive to Save and Open file.
JS error as follows:
file-control.php?action=load&file=|.htaccess&csrf=b7ccc5c256f81005e126df22959b9b80&lineNumber=undef…:40 Uncaught SyntaxError: missing ) after argument list

**Comment by mattpass** [comment]
Another user reported a similar issue and let me borrow their server to track down & fix things. Their issue was not being able to save a file that contained 'curl'.

While this too was a server restriction, ICEcoder wasn't handling denied HTTP error responses well (eg 400, 403 etc) and was jamming up which could only be resolved with a browser reload.

Made some changes to now handle this nicely and so done and closed. :-)

**Comment by mjheidari** [comment]
i have this error to.it's for Mod security. 
log:
ModSecurity: Access denied with code 403 (phase 2). Pattern match "<\\\\?(?!xml\\\\s)" at ARGS:changes. [file "/usr/local/cwaf/rules/01_Global_Generic.conf"] [line "63"] [id "211220"] [rev "3"] [msg "COMODO WAF: PHP Injection Attack||..... [uri "lib/file-control-xhr.php"] .....
