### ISSUE TITLE
Terminal improvements

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#365]
Some good suggestions have come up re Terminal usage, see issue #348, but summary details would be:

* 2 level authentication - ICEcoder login details or server login details (user can enter either)
* Choices of Bash, ZSH
* Open in new tab, panel, or seperate window options
* Right click on a file and choose to run in Terminal

**Comment by mattpass** [comment]
Also look into Xwiterm (https://code.google.com/p/xwiterm/) and PHP Shell (http://phpshell.sourceforge.net/)

**Comment by bfishman** [comment]
-Tab autocompletion for terminal

**Comment by mattpass** [comment]
OK, will see what I can do :-)

**Comment by bfishman** [comment]
Just a suggestion for the future :)  higher on my list would be true ssh access via the browser, as the php 'sandbox'  can be somewhat limiting.  User $PATH not being loaded, etc.

**Comment by mattpass** [comment]
That'd be great - if you know of a SSH solution I'd happily look into it! :-)

**Comment by bfishman** [comment]
Check out: https://github.com/liftoff/GateOne

It works great, although I'm currently having difficulties in my attempt to proxy it behind my Apache web server on Port 80 because it uses an internal tornado web server. I believe it can be integrated into an existing web page, however. Haven't explored that route yet.

**Comment by mattpass** [comment]
I did come across Gate One quite a while back but for some reason thought it was a no-go. Let me look into it - may well be a viable solution - especially if you rate it.

**Comment by mattpass** [comment]
Also came across this a while back - https://github.com/paradoxxxzero/butterfly

**Comment by bfishman** [comment]
Nice, thanks for the link I will check that one out too.

**Comment by mattpass** [comment]
This issue now closed and will be covered under #660.
