### ISSUE TITLE
Issue with CTRL+Alt+b/g tag wrapper

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#423]
According to @darkosvitic, the CTRL+Alt+b tag wrapper is used by those with a Croatian keyboard to get the } character. Need to consider removing or using an alternative? Also a problem with CTRL+Alt+g which is used by ].

See keyboard layout:
http://freepages.genealogy.rootsweb.ancestry.com/~elainetmaddox/czech_keyboard.jpg

**Comment by Nippey** [comment]
Hi, 
looks like I can attach myself to this issue.

On the German Keyboard, "[" is Ctrl+Alt+8.
So, I don't get "[" but "<li></li>".
http://en.wikipedia.org/wiki/German_keyboard_layout#mediaviewer/File:KB_Germany.svg

Everything is at other places depending on the language :/
For me it would be okay to have the option to deactivate single shortcuts.

BR

**Comment by mattpass** [comment]
After some looking into this, it seems the only sensible option is to add a setting to the Settings screen allowing you to turn on/off tag wrappers.

**Comment by mattpass** [comment]
Decided in the end to drop tag wrappers for b, I, strong, em and li as they cause too many problems with different keyboard types and finding a good alternative was very difficult. Keeping only the simpler and more structural and hyperlink based list of - div, span, p, a and h1-h3. Done and closing.
