### ISSUE TITLE
Suggestions for improvements to the search box

### ISSUE THREAD

**Issue by lzh370** [mattpass/ICEcoder#436]
@mattpass HI.
For the search box:
1.Made the search box pops up layers, or can be extended. 
2.Supports multi-line search and replace multiple lines. 
3.In the result layer Click the file name to jump directly to the line and highlight, it seems does not work. 
4.Do not cover the browser Ctrl + F search box, the search for a single page for the browser's search box more convenient.

In addition:
1.When the mouse to scroll to the top of edit area, do not switch between documents. Only the mouse on the scroll when the switch opened tab document.
2.Sometimes when you delete a directory fails, it might be adding a failure reminder.

**Comment by mattpass** [comment]
Closing this issue as a few items covered and the only remaining one is re multiline find and replace, which I've added as new issue #565.
