### ISSUE TITLE
FTP integration

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#490]
New details on the planned FTP integration since details in #240 are now not correct.

Users will be able to add a host, port, username, local and remote paths under a reference name and course be able to edit/remove at any time. When then connecting, it will ask for a password. When connected it will ask if you want to clone to your local path or work on the remote server.

Check out details of issue #240 for older details and some good lib suggestions.

**Comment by ruimpsantos** [comment]
Hello.
Any news about ftp integration? I need to connect to remote ftp servers, and this is crucial if i want to keep working with ICEcoder.

Thanks for all the great work you've done.

**Comment by mattpass** [comment]
Think I will start work on it this upcoming week so we have a version usable by v5.3 (est end Aug).

**Comment by mattpass** [comment]
FTP integration well uinderway and a basic implementation should be committed today. One item I've noticed so far is that the canvas for image hovers doesn't work with FTP:

```
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
```

Need to allow cross-origin data in the case of sourcing over FTP.

**Comment by Atatoth** [comment]
Btw. Do you remember about ftp over tls?? Last time is most popular on hosting company

**Comment by mattpass** [comment]
If I enable this also I think we're OK to work over TLS?

**Comment by mattpass** [comment]
(Sorry, see updated comment re using secure option details at http://php.net/manual/en/function.ftp-ssl-connect.php)

**Comment by mattpass** [comment]
This is going to be introduced in 5 stages, as follows:

- [ ] List, open, save - by v5.2
- [ ] Other file operations (rename, delete etc) - by v5.3
- [ ] Fixing obscure issues (eg, hover over image & cross-site-origin) - by v5.3
- [ ] FTP site manager - by v5.3
- [ ] Full check thru to complete - by v5.4

**Comment by mattpass** [comment]
Seems like there is a CORS issue with cross domain image loading into canvas: http://stackoverflow.com/questions/28547288/no-access-control-allow-origin-header-is-present-on-the-requested-resource-err

**Comment by mattpass** [comment]
OK, changes committed which means you can now specify FTP details and view file list, open and save. This is a super early version and saving needs to be completed, plus other file processes (save as, delete etc), so shouldn't be considered production ready.

However, if you are interested in using FTP within ICEcoder, you can specify details at the top of lib/settings.php now (also set $ftpSiteConn value to 1 or another number) and reload ICEcoder. It then works over FTP using those details. It's lightning quick too! Seems quicker than using many of the FTP client programs I have!!

All feedback welcomed, please just remember this is completed at the most basic of levels.

**Comment by mattpass** [comment]
List of processes to cover:

- [x] List Files/Dirs
- [x] Open File
- [ ] Save (to be finished)
- [ ] Save As
- [x] New Folder
- [ ] Move File/Folder
- [ ] Rename File/Folder
- [ ] Paste File/Folder
- [ ] Upload File(s)
- [ ] Delete File(s)/Folder(s)
- [ ] Replace Text in a File
- [x] Change perms
- [ ] Check for a file/dir
- [ ] JSON data returned dirname, filesize, file_exists, is_dir etc

**Comment by mattpass** [comment]
Items found that also don't work/need looking into:
- [ ] Permissions modal screen won't show in FTP mode
- [ ] Replace alert() with ICEcoder's message()

**Comment by mattpass** [comment]
OK going to close this issue and start a new one as a final list of what remans to be done now.
