### ISSUE TITLE
iframe is not supporting on the ice coder

### ISSUE THREAD

**Issue by Mashpy** [mattpass/ICEcoder#523]
i have put ice code editor one of my server.

now I want to call this ice website using iframe. I can see blank page.

**Comment by mattpass** [comment]
Mmmm it's not really designed to work within an iframe. May be a future thing to cover but for now just won't work that way.

**Comment by Mashpy** [comment]
I think you have turned off the iframe feature. which prevent the icecoder to show in iframe.

you have put the code in lib/header.php file.

**Comment by mattpass** [comment]
Ah yes of course.

If you disable that header param it may have usage issues still, not sure. Wasn't designed to run in an iframe really.

**Comment by Mashpy** [comment]
can u give me any idea to make it support of iframe? I need to use this script. if u help me i can work on this script. where is the main problem of supporting iframe and why u have disabled it.

**Comment by mattpass** [comment]
The header param has been set to avoid potential security/hacking issues (clickjacking etc).

You can disable it and then most likely all will work OK if you change all JS instances of top.ICEcoder to document.ICEcoder or parent.ICEcoder so the targets are the iframe rather than leaking to the new parent level (your framework).

Will be 100's of references to changr but happy to accept a pull request if you check all changes work OK.

**Comment by pietrondo** [comment]
I also need this "trick" but I would use the icecoder git version. Is "tecnically" possible do this with a plugin?

**Comment by mattpass** [comment]
No plugin would make it work as described. The hard work would need to be put in to change all the references so it could run from anywhere, such as within an iFrame.

**Comment by RDaneelOlivav** [comment]
Hi, same issue here. Just commenting the lib/header.php line
header("X-Frame-Options: SAMEORIGIN");
It lets you embed it but when logged in gives an error:

Uncaught SecurityError: Blocked a frame with origin "http://hoster_ip" from accessing a frame with origin "http://localhost:8000". Protocols, domains, and ports must match.

Anything new on this matter?

**Comment by Mashpy** [comment]
As iframe is not supported on this so I moved to Codiad IDE.
