### ISSUE TITLE
Change the session cookie to be on the /ICEcoder/ path only.

### ISSUE THREAD

**Issue by Nippey** [mattpass/ICEcoder#528]
Hi,

I use ICEcoder on a server with other scripts also using PHP's session_start() and PHPSESSID mechanism.
Unfortunately, if I logout from one of these, I will automatically kicked out of the others.
This includes killing the possibility to save changed files.

I would appreciate, if the session cookie of ICEcoder would not interfere with other cookies by just sticking to ICEcoders root dir :)

This should be achievable with the session.cookie_path = "/ICEcoder/" variable.

BR Nippey

**Comment by mattpass** [comment]
Agreed. It was actually being saved to ICEcoder's /tmp dir but for security I looked recently to use the standard session dir (OS temp).

However, this is causing some usage issues and also the session ending issue you mention. Going to revert back today.

**Comment by Nippey** [comment]
Hi,
just to be clear that we don't talk about different topics :)

What I mean is the Cookie-Path the Cookie is stored for in the Browser.
The default is "/" which means that this cookie is valid for all subdirectories of "www.example.com".
So, a session stored in such cookie is valid for each subfolder.
An alternative is, to define a cookie just to a certain subfolder "/ICEcoder/".
If I now visit "www.example.com/OtherProject", no cookie would be sent by the browser.

**Comment by mattpass** [comment]
Ah, yes, we were talking about different topics. Well spotted.

Your thoughts there sound great. TBH, I didn't know you could have separate cookies for subdir paths, I thought it was domain/subdomain based. Good to know you can have them for separate dirs!

Will implement your tweak as described and also roll back my server storage path of the PHP session cookie anyway.

Will let you know when your tweak is done - thanks!

**Comment by Nippey** [comment]
Oh, one more thing, I just learned a few seconds ago:
There are two ways to make sure, no confusion is generated on the server. Both work independently:

    // --A--
    //Make sure the cookie will only we sent by the browser if we are in the ICEcoder subdirectory
    //NOTE: If there is a second cookie, valid for "/", both with the same variable, 
    //      the server still seems to get BOTH variables like: "PHPSESSID=12345, PHPSESSID=67890"
    // dirname($_SERVER['SCRIPT_NAME']) can only be used if all php files reside in the same directory
    session_set_cookie_params(0,dirname($_SERVER['SCRIPT_NAME']));

    // --B--
    //Make sure the cookie uses a unique cookie-variable to identify its session
    //This seems to be the most effective method to make sessions unique. Then we can just ignore messing with the cookie path.
    session_name('PHPSESSID_ICECODER');

    session_start();

Haha, I never stop learning new things ^^

**Comment by mattpass** [comment]
Both sound good I think. Going to look into this later today and then we can clear this issue and #524.

**Comment by mattpass** [comment]
Am using these params now, your ideas here also incorporated:
```
// Start a session if we haven't already
if(!isset($_SESSION)) {
	ini_set('session.use_cookies','1');				// Use cookies not URL parameters 
	ini_set('session.use_only_cookies','1');			// Force use of cookies and nothing else
	ini_set('session.name','ICEcoder_Cookie');			// Set a seperate cookie session name
	ini_set('session.cookie_lifetime','0');        			// Until the browser restarts by default
	ini_set('session.cookie_domain','');				// This domain only
	ini_set('session.cookie_path',dirname(__FILE__).'../'); 	// ICEcoder path only
	ini_set('session.use_trans_sid','0');				// Ensure this insecure feature is disabled
	ini_set('session.hash_function','sha512');			// Use Sha512 for session
	ini_set('session.hash_bits_per_character','6');			// Specify hash scheme of 0-9,a-v,A-Z,-,,
	ini_set('session.use_strict_mode','1');				// Reject any session ID that was user provided and not generated by the session
	ini_set('session.httponly','1');				// Only allow http protocol (ie, not JS) access to the cookie
	ini_set('session.save_path',dirname(__FILE__).'/../tmp');	// Localise the session files to /tmp
	if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
		ini_set('session.cookie_secure','1');			// Only allows access to session ID when protocol is HTTPS, switched on under 'if https' condition 
	}
        session_regenerate_id(true);					// Create a new ID to help prevent fixation
        @session_start();						// Finally, start the session!
}
```

**Comment by mattpass** [comment]
Going to close this as I think all done here, please reopen if I need to look into anything here. Thanks for your help also! :+1:
