### ISSUE TITLE
CSRF Issue with IE (11)

### ISSUE THREAD

**Issue by rjahn** [mattpass/ICEcoder#529]
* Fresh install of master clone
* tried with Chrome (worked)
* tried with FF (worked)
* tried with IE:

CSRF issue:
 REQUEST: d83aa0e39f8425318b7da5f6a0138911
 SESSION: 6c3751aa4e43de02cbdad525bf59a174
 FILE: /edit/lib/login.php
 GET: array ( )
 POST: array (XXXXX', 'submit' => 'login', 'csrf' => 'd83aa0e39f8425318b7da5f6a0138911', )

Every login attempt creates a new session?

**Comment by mattpass** [comment]
Are you sure - can you try again? I have found some issues re IE11, but not CSRF and session based. As sessions are controlled on the server side, it shouldn't matter what browser you are using.

**Comment by rjahn** [comment]
Yes, tried it and got same message again:

CSRF issue:
 REQUEST: 9547e88785d45b6260424068b712e3f5
 SESSION: 95b9fae211c2bf2702c4ae9759f18843
 FILE: /edit/lib/login.php
 GET: array ( )
 POST: array ( 'username' => '', 'password' => '', 'submit' => 'login', 'csrf' => '9547e88785d45b6260424068b712e3f5', )

I didn't enter username/password, simply pressed login.

I cleared the temp folder before testing and after I got the message, the file had 3 sess_* files, so I don't think it's a general problem.

Not sure, but you set some headers in headers.php and it could be an IE related problem...

**Comment by mattpass** [comment]
Sorry for the delay here. I can reproduce the same issue in IE11. Seems it's the:

```
ini_set('session.cookie_path',str_replace($_SERVER['DOCUMENT_ROOT'],'',dirname(dirname(__FILE__)))); 	// ICEcoder path only
```

...line in lib/settings-common.php. There is a JavaScript error then which I'll fix, but wonder if commenting this line out gets you logged in without a CSRF issue also?

**Comment by rjahn** [comment]
If I comment out the line, no error appears and after pressing login, I got redirected to the login page.
No login possible!

**Comment by mattpass** [comment]
Seems like commenting out that line avoids the CSRF issues but maybe there's another issue there.

Try commenting out lines 20-35 in that file and it should work? If so, great! Tho I would like to know what's stopping you logging in. :-/

**Comment by rjahn** [comment]
Sorry, I had debug code from my last tests and this caused the login problem:

Re-test:

Login works with without this line:
  ini_set('session.cookie_path',str_replace($_SERVER['DOCUMENT_ROOT'],'',dirname(dirname(__FILE__))));    // ICEcoder path only

and also without lines 20-35.

BUT after LOGIN, the progress/waiting animation remains visible. IE only?

**Comment by andrey012** [comment]
I think I have reproduced this IE problem and I think I have fixed it in 4be54f8d14bea38e3803d19df13b36fd4e602a85: 
-		top.filesFrame.contentWindow.focus();
+		var filesFrame = top.document.getElementById('filesFrame');
+		var contentWindow = filesFrame.contentWindow.focus();

**Comment by andrey012** [comment]
BTW, Matt, it looks like IE does not support getting an element by its id as top.filesFrame, and there are numerous usages of this kind of reference in the code, I have just fixed one of them. 
I think it would be good to replace all top.filesFrame with top.getElementById('filesFrame') or something like that.

**Comment by mattpass** [comment]
Thanks for the update @rjahn - looks like @andrey012 has pinpointed this and indeed a bigger IE11 issue.

@andrey012 - this could be my mistake and maybe should be top.ICEcoder.filesFrame (as the initAliases function namespaces filesFrame under top.ICEcoder just as you're doing in your fix?)

Am AFK at the moment but should work the same and can try later. Anyways, you're probably right - all top.filesFrame refs will need changing!

**Comment by Uxspy** [comment]
Guys, we met the same issue in our product, here's link to IE11 bug: 
https://connect.microsoft.com/IE/feedback/details/810700/subject-ie11-is-losing-cookie-information-and-thus-becoming-detached-from-a-web-application-session

**Comment by mattpass** [comment]
OK, CSRF issue resolved by removing that line and fixed the approx. 10 instances where we targeted filesFrame badly. Should be (top.ICEcoder.filesFrame). Doesn't make a difference on Chrome etc but IE seems to have DOM selection issues otherwise and recent commits now fix these. Thanks for reports & help everyone - closing!
