### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by Atatoth** [mattpass/ICEcoder#540]
when i try to log in page refresh and stay in this same place with no error.

v 5.0 beta
nginx/1.2.1
PHP Version 5.4.36-0+deb7u3

**Comment by mattpass** [comment]
Could try opening lib/settings-common.php and removing lines 20-35, so that section looks like:

```
// Start a session if we haven't already
if(!isset($_SESSION)) {
        @session_start();						// Finally, start the session!
}
```

Then close down all browser windows and try again? If you can get in then, one of those session parameters is causing an issue. It may possibly be the ```ini_set('session.use_strict_mode','1');``` line which is PHP 5.5+, but should silently fail if it can't be used.

**Comment by Liroy** [comment]
i have only

```php
if(!isset($_SESSION)) {
	ini_set('session.use_cookies','1');				// Use cookies not URL parameters 
	ini_set('session.use_only_cookies','1');			// Force use of cookies and nothing else
	ini_set('session.name','ICEcoder_Cookie');			// Set a seperate cookie session name
	ini_set('session.cookie_lifetime','0');        			// Until the browser restarts by default
	ini_set('session.cookie_domain','');				// This domain only
	ini_set('session.cookie_path',str_replace($_SERVER['DOCUMENT_ROOT'],'',dirname(dirname(__FILE__)))); 	// ICEcoder path only
	ini_set('session.use_trans_sid','0');				// Ensure this insecure feature is disabled
	ini_set('session.hash_function','sha512');			// Use Sha512 for session
	ini_set('session.hash_bits_per_character','6');			// Specify hash scheme of 0-9,a-v,A-Z,-,,
	ini_set('session.use_strict_mode','1');				// Reject any session ID that was user provided and not generated by the session
	ini_set('session.httponly','1');				// Only allow http protocol (ie, not JS) access to the cookie
	ini_set('session.save_path',dirname(__FILE__).'/../tmp');	// Localise the session files to /tmp
	if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
		ini_set('session.cookie_secure','1');			// Only allows access to session ID when protocol is HTTPS, switched on under 'if https' condition 
	}
        session_regenerate_id(true);					// Create a new ID to help prevent fixation
        @session_start();						// Finally, start the session!
}
```

**Comment by mattpass** [comment]
@Liroy - You need to remove the extra lines so it looks like my example. Worth reading my comment above https://github.com/mattpass/ICEcoder/issues/540#issuecomment-75244067

**Comment by Liroy** [comment]
ohhh sorry :P

**Comment by mattpass** [comment]
No worries @Liroy :-) These new session settings have caused people a few problems, which I'll look to iron out for the full v5 release.

**Comment by Liroy** [comment]
on nginx with you answer and with  comment csfr error working
on apache working without any changes

**Comment by mattpass** [comment]
@Liroy - yeah, think I need to take some of them out and it should solve issues, but knowing which ones cause a real problem for people is a bit unknown.

I suspect it's the ```session.cookie_domain```, ```session.use_strict_mode``` or ```session.httponly``` lines but can't be sure.

**Comment by Liroy** [comment]
if you need i can help :) tell me how :)

**Comment by mattpass** [comment]
@Liroy That'd be great. You need to comment out each line with a // at the start. Then close your browser windows, open one and make sure ICEcoder works OK.

Then remove comments from some line(s), close browser windows, open ICEcoder, repeating the test to ensure it works.

Keep going till you find the line(s) that are the problem.

**Comment by Atatoth** [comment]
ok i test

**Comment by Atatoth** [comment]
```php
ini_set('session.cookie_path',str_replace($_SERVER['DOCUMENT_ROOT'],'',dirname(dirname(__FILE__)))); 	// ICEcoder path only
```
is problematic on nginx and php-fpm when login

**Comment by mattpass** [comment]
That was indeed the problem line, which I've now commented out of usage. Thanks for your help on this, all working now and so closing.
