### ISSUE TITLE
Problem with CSRF and symlink

### ISSUE THREAD

**Issue by sewid** [mattpass/ICEcoder#541]
Hi there,

I have a icecoder installation on my webspace and many domains and subdomains hosted. When I add a symlink ('ice') to a subdomain, that points to the icecoder installation and I try to open this symlink, the screen to set the password appears.

When I now enter a password and press enter, I get a CSRF error:

    CSRF issue:
    REQUEST: a2e7468e0ce0505cdd3265fc7af00884
    SESSION: e38ace40c964573982ff49b3658b260f
    FILE: /ice/lib/login.php
    GET: array ( )
    POST: array ( 'password' => 'example', 'submit' => 'set password', 'checkUpdates' => 'true', 'csrf' => 'a2e7468e0ce0505cdd3265fc7af00884', )

When I open icecoder directly (without symlink and a subdomain, pointing to the installation), everything works fine.

Best regards,
Sebastian

**Comment by mattpass** [comment]
If you keep getting different values in the 'SESSION:' part, I suspect this is because of the following setting in lib/settings-common.php (line 24)
```
ini_set('session.cookie_domain','');				// This domain only
```

Could try commenting out that line, closing all browser windows to kill sessions and try again.

Maybe fixes the problem? May also be line 25 of that file re cookie_paths, try commenting out that one?

**Comment by sewid** [comment]
Hi mattpass,

it's line 25:
    	
    ini_set('session.cookie_path',str_replace($_SERVER['DOCUMENT_ROOT'],'',dirname(dirname(__FILE__)))); 	// ICEcoder path only

If I comment that line out, it's working. Commenting out line 24 doesn't change anything.

Additional note: I use the v5 beta.

Best regards,
Sebastian

**Comment by mattpass** [comment]
Great many thanks @sewid :-)

**Comment by mattpass** [comment]
Thanks for the info on this. I've commented out that line in ICEcoder now, as it was also causing lost session issues in IE (Chrome, Firefox etc works fine). So was causing issues on 2 fronts, but no more! :-)
