### ISSUE TITLE
Permissions not set properly when uploading

### ISSUE THREAD

**Issue by Dunky13** [mattpass/ICEcoder#543]
I opened the *config__settings.php* file and changed: *newDirPerms* and *newFilePerms* to 775 (due to my system requiring these permissions) but when I uploaded a file it set the permissions to 644 - I couldn't find the source for settings permissions - so please look into it.

**Comment by Dunky13** [comment]
I fixed it temporarily by changing the file: *on-file-upload.php*
I added:
```php
$uploadDir=$docRoot.$iceRoot.str_replace("..","",str_replace("|","/",strClean($_POST['folder'])."/"));
foreach($uploads as $current) {
	$file=$uploadDir.$current->name;
	if ($setPerms) {
		chmod($file,octdec($ICEcoder['newFilePerms']));
	}
}
```

**Comment by mattpass** [comment]
Good spot - many thanks!

**Comment by mattpass** [comment]
Added something pretty similar into the core workings of ICEcoder. Many thanks! Closing.
