### ISSUE TITLE
'Folder Empty Loop' When trying to Import from GitHub

### ISSUE THREAD

**Issue by Celtic-Parser** [mattpass/ICEcoder#544]
I have been getting this same error on various installs:

`Your local folder is empty, would you like to clone from http://[MY GIT REPO]`

Click on `OK` and it just goes into a loop with the same dialog popping.

I get the same response on Apache2 / php v5.5.3 ( three different different Apache installs  ) and on Nginx w/ php v5.5.22.  I also ran the app in Chrome and IE. All installs are on Ubuntu 1404 and I tried with various permissions.  I had also installed ICEcoder v4.5 with the same issue.  Something wrong with my installs?  What should I look for.  Your help will be greatly appreciated. 

Thnx

-j

**Comment by mattpass** [comment]
Thanks for letting me know. So, the files aren't pulled in from your repo at all then?

**Comment by mattpass** [comment]
Sounds like maybe the details you're entering aren't quite what it's expecting? I can add a new path pair using the details:

Local path:
/dotfilesHERE
Remote GitHub Path:
http://github.com/mattpass/dotfiles

...and click 'Add' then 'Choose'. It tells me the folder is empty (as /dotfilesHERE doesn't exist yet), would I line to clone it and I click OK. It then adds that /dotfilesHERE dir and clones the files to it, plus switches to view that dir as top of the file manager tree.

Can you confirm if you can do the same? Will close the issue assuming all is fine, but please reopen if you get a different result.
