### ISSUE TITLE
X-XSS-Protection error

### ISSUE THREAD

**Issue by Dunky13** [mattpass/ICEcoder#547]
When changing settings in ICECoder and save it, the CSS for code style is suddenly gone and get many errors: *Error parsing header X-XSS-Protection: 1; mode=block;, 1; mode=block: unrecognized directive at character position 14. The default protections will be applied* 
Not sure if related to eachother.

Using Chrome 41

**Comment by mattpass** [comment]
OK, thanks - I'll mark as a bug and investigate.

**Comment by mattpass** [comment]
Think this issue was actually caused by another which I've now fixed. If you can test against the latest code in the repo and still get issues, please let me know but going to close this as I think it's now fixed.

**Comment by pavanvamsi3** [comment]
Hi, I'm facing the same issue in my project. Can you guide me with the solution please?

**Comment by mattpass** [comment]
Hi @pavanvamsi3 - unfortunately that was almost a year ago and I can't remember what the fix was now. It's also a closed issue here. Do you get the exact same error report? Please also let me know what browser, version, OS and version of ICEcoder you're using?

**Comment by pavanvamsi3** [comment]
Hi @mattpass Thanks for the time. It's solved. 
While setting the header I had to use replace=true, i.e if the header already exists I had to replace it. I've faced this problem in Chrome 49.* and Safari.

**Comment by mattpass** [comment]
Ah I see @pavanvamsi3 - it's weird that the headers are set twice as it should only apply these if headers aren't already sent: https://github.com/mattpass/ICEcoder/blob/master/lib/headers.php#L30-L39

I'm going to reopen this issue as I think it would be good to remove the specific header items (if they exist) prior to them being set) to avoid duplicates or perhaps the first being used, my 2nd set applied not being considered etc etc.

**Comment by pavanvamsi3** [comment]
I'm not sure if they're already existing or not but, replace made the trick.

**Comment by mattpass** [comment]
This has very rarely been an issue and maybe not something that needs to be in the repo afterall. If it crops up for anyone else I'll consider it but for now closing again.
