### ISSUE TITLE
Javascript error - "Uncaught SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by musicmunky** [mattpass/ICEcoder#548]
Just redownloaded the v4.5 package and am now encountering this error when attempting to save/open any files.  Permissions are all either 755 or 775.
It says it's failing on this snippet in index.php (according to chrome/firefox):

```
window.onbeforeunload = function() {
	for(var i=1;i<=ICEcoder.savedPoints.length;i++) {
		if (ICEcoder.savedPoints[i-1]!=top.ICEcoder.getcMInstance(i).changeGeneration()) {
			return "You have some unsaved changes.";
		}
	}
}
```

I know that's partially generated from PHP, but nothing appears to be out of the ordinary.  Anyone have any ideas?

**Comment by mattpass** [comment]
I will check this out but AFAIK it should work without this issue. Can you confirm that with dev tools open after a CTRL+F5 refresh it still has the problem?

**Comment by musicmunky** [comment]
Yep - this is from just a few minutes ago.  Cleared my cache, restarted the browser, still getting the error:
![error](https://cloud.githubusercontent.com/assets/4141041/6982875/6bb8ec44-d9e5-11e4-89f1-c618867a9a96.PNG)

**Comment by mattpass** [comment]
Can you let me know the line number & file the dev tools is referring to (not in your screenshot).

Would also be v handy if you can click that link in dev tools, it displays the error line, copy and paste the error.

Many thanks!

**Comment by musicmunky** [comment]
My mistake - knew I was forgetting something, sorry!!
Error is:
**"Uncaught SyntaxError: Unexpected token        index.php:17"**

It's failing on the closing brace of the if-statement below:
````
window.onbeforeunload = function() {
	for(var i=1;i<=ICEcoder.savedPoints.length;i++) {
		if (ICEcoder.savedPoints[i-1]!=top.ICEcoder.getcMInstance(i).changeGeneration()) {
			return "You have some unsaved changes.";
		}  **<== LINE 17 ACCORDING TO DEV TOOLS**
	}
}
````
Let me know if you need more info - thanks

**Comment by musicmunky** [comment]
Still not sure what the issue was, but I went ahead and bought the 5.0 beta and it's working correctly.  I'll go ahead and close this issue.

**Comment by mattpass** [comment]
@musicmunky Was a strange issue. Well, as no one else reported the same and you've moved onto v5.0 beta (thanks for the donation BTW!), I'm happy to let this one go. Thanks.
