### ISSUE TITLE
Typo & bug in lib/updater.php

### ISSUE THREAD

**Issue by raffiismail** [mattpass/ICEcoder#563]
Line 223:

echo '<script>alert("'.$t['Update appears to...'].'");window.location = "../?display=updated&csrf='.$_SESSION["csrf"].";</script>';

Double quote used to open string, but single quote used to close. Instead, it should be:

echo '<script>alert("'.$t['Update appears to...'].'");window.location = "../?display=updated&csrf='.$_SESSION["csrf"].';</script>';

This bug causes updater.php to not run properly when updating from 5.0 beta, even when it is fixed, the updater runs, makes the necessary backups and completes, but ICEcoder does not start (faced with blank page) after update.

**Comment by mattpass** [comment]
OK thanks for the info. Will look into this and fix shortly.

**Comment by MECU** [comment]
This is line 223:

`echo '<script>alert("'.$t['Update appears to...'].'");window.location = "../?display=updated&csrf='.$_SESSION["csrf"].'";</script>';`

https://github.com/mattpass/ICEcoder/blob/master/lib/updater.php

I don't see the problem nor does 3 syntax checkers.

**Comment by mattpass** [comment]
There's no syntax error here, but there is a problem with the updater. The settings are now created on the fly and not available to use as per previous versions of ICEcoder. The result is a blank lib/config___settings.php file, so it won't start up (and you get a blank screen).

Going to write a fix for this now.

**Comment by mattpass** [comment]
OK, wrote a fix, but people won't get to see a working updater till after they've got the latest code from this repo, or v5.1. Done so closing tho.
