### ISSUE TITLE
Menu missing in languages other than english

### ISSUE THREAD

**Issue by Nippey** [mattpass/ICEcoder#564]
Hi,

I tried to switch ICEcoder v5.0 to German today.
I found that the menu "Source" was missing then. This also applies to netherlands.

Also, in english.php is an entry for "Source" that is missing for other files.

I would propose one or more of the following behaviours for improved translation:

* If a lookup fails, default to English.
* If a lookup fails, create a log/filesystem entry.
* If a lookup fails, colourise or format the English word.

BTW:
"Source" translates to German "Quelle"

BR
Nippey

**Comment by mattpass** [comment]
Mmmm it should default to English if the chosen language doesn't have the text for an item. Just as per your first suggestion. Will look into this!

**Comment by mattpass** [comment]
I looked into this and it seems to be defaulting to English OK? I'll close the issue as all seems fine, but if you still experience this problem with a fresh copy of v5.1 please feel free to reopen.

**Comment by mattpass** [comment]
BTW - have big plans for a multi-language system that's much more in-sync between the languages. Coming soon! :-)
