### ISSUE TITLE
Saving files with over 360 lines fails

### ISSUE THREAD

**Issue by hybiepoo** [mattpass/ICEcoder#572]
I have a feeling this may be a php setting needing changed, but not sure.
When trying to save some files, the save hangs with the "Saving" message in the bottom left.

Console debugger shows this:
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

I think this is probably a php setting needing to be increased more than anything. This is a dedicated server, so I can change any setting that needs it.

**Comment by hybiepoo** [comment]
Actually this is not to do with file size, or number of lines as I just saved a .htaccess of larger size and 800+ lines. It must be something to do with the content of the files.

**Comment by mattpass** [comment]
The contents of the file shouldn't matter. If you try again with the same content does it work OK?

**Comment by hybiepoo** [comment]
No,  tried a completely new file with the same content and it doesn't work. 
I was able to write a much bigger htaccess file no problems.

You can try the same content as me here :
https://code.google.com/p/dragonfly-cms/source/browse/includes/dragonfly/forums/forum.php?name=v10

I have another site that it works fine on. Not sure why yet. Sometimes if I add one line at a time it will let me save more,  but it eventually dies again.

**Comment by hybiepoo** [comment]
I tried creating the file in the root folder and the same thing happens.
What apache and php settings are involved when the file is written? I can compare the settings on both sites.

**Comment by hybiepoo** [comment]
Ok, both sites are now running 5.4.42 and one site is still broken.
The one that is not working is not using SSL.
However, the one that is working is using SSL.
If I connect using http, that one breaks too!
I wonder if this is a proxy issue.

**Comment by hybiepoo** [comment]
Yes, it's a proxy issue. You can close off this issue, thanks.

**Comment by mattpass** [comment]
Ah, glad you figured it out and all is working OK now. :-) Closing.
