### ISSUE TITLE
Restrict file type(s)

### ISSUE THREAD

**Issue by firstygoldfish** [mattpass/ICEcoder#574]
In order to maintain some security on my site I want to only allow client side processed files only. I.e. html,js,css etc. I want to restrict/ban php for example to avoid site damage/hacking.

There is mention of restrict files and ban files but I can see no mention in the manual.

Is there functionality to acheive this already?

Thanks

**Comment by mattpass** [comment]
Yes, it's done within the Edit > Settings section (and then the new 'Security' tab if you have the very latest version from GitHub. Within the input field for 'banned files/folders' you can enter a comma separated list of files and folders you don't want to provide access for. To ban php files you would need to simply enter '.php'.

However, I've just noticed a bug with this - it won't show .php files anymore in the file manager or search results, but you can still save a new php file or open with CTRL+O and enter the path to it. For me to fix so marking this issue as a bug!

**Comment by mattpass** [comment]
Will also need to cover renaming as you could save a PHP file as blah.xyz, then rename to blah.php to get around the restriction otherwise. Include find and replace in filenames.

**Comment by mattpass** [comment]
Now checking file requested isn't on banned list before getting or setting. Done and closing.
