### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by anagnam** [mattpass/ICEcoder#575]
Hi @mattpass , 
I tried installing V5.1 but after typing in a password, I cannot login. Its stuck at login.php
Any ideas?

**Comment by ruimpsantos** [comment]
I'm having same issue, but since i'm trying it out on a test environment, i set "loginRequired"		=> true, on config___settings.php under lib folder.

In my case it seems to be some issue with sessions. I tried running test.php and I'm having problems on TEST 2 of 3: Sessions.

For now I'm overriding this issue, because my intention is to test it.

**Comment by mattpass** [comment]
Thanks for the reports - your issues would indeed be down to sessions it seems. @ruimpsantos you did the right thing by trying out the test file, this especially helps find if you have session issues, @anagnam you may want to try the same.

Not sure what I can do to help with session issues on servers really if the simpe tests fail. :-/

**Comment by anagnam** [comment]
@mattpass I tried the suggestions. make loginRequired to false but still I cannot make a folder or a file. its not showing up either. Dont know whats going on. Im on a shared hosting btw.

**Comment by N6REJ** [comment]
I'm having the same issue... and same result, if I change config__settings to required = false it works.
http://jowwow.net/icecoder/test.php

**Comment by mattpass** [comment]
@n6rej Looks like somethings up with your PHP sessions setup. test.php is a standalone file and should pass without issue.

**Comment by N6REJ** [comment]
we got that part working but can't access the files.. just comes up 
blank with this error...

[14-Aug-2015 22:24:27 UTC] PHP Notice: Undefined variable: t in 
/home/jowwow/public_html/icecoder/lib/headers.php on line 21

die($t['Bad CSRF token...']."

^ line 21


Bear

**Comment by anagnam** [comment]
@mattpass  by making "loginRequired" => false, i was able to get to the editor. problem now is that I cannot create a new file or folder. it just doesn't work. do you know why?

**Comment by N6REJ** [comment]
no, i have the same problem
Bear

**Comment by mattpass** [comment]
Found that @anagnam had session issues too and works fine after resolving them. Hope that was the same for you too Bear. Closing.
