### ISSUE TITLE
Line Wrap Issue

### ISSUE THREAD

**Issue by LeRouxVanWyk** [mattpass/ICEcoder#584]
When setting line wrap off, the horizontal scroller causes a page cursor reset.

**Comment by mattpass** [comment]
Thanks - could you provide some more details and maybe even some screenshots to show the issue specifically so I can investigate?

**Comment by LeRouxVanWyk** [comment]
It's not really something that I can capture on a screenshot. The bug is very easy to replicate.
Simply de-activate line wrapping and then create some code which spans more than the code editor window. Once you use the horizontal scrollbar to move to the code and start editing the editor moves the cursor back to the top of the page.

**Comment by mattpass** [comment]
Ah yes I see the problem now. Don't think you even need to start editing. Simply scroll horizontally and it scrolls vertically to the top of the page. Going to mark this as a v5.3 issue as it's a priority to fix. Thanks!

**Comment by mattpass** [comment]
OK, made some adjustments here to avoid a juddering scrollbar which causes this issue. Pane scroll positions sync when going into diiff mode, pane scroll position syncing only happens in diff mode and only matches after a 0ms tickover to give priority to scroll controls and avoiding the judder, which gave jumpy (and wrong) scroll positions. Should be all fixed here so closing.
