### ISSUE TITLE
Class Browser

### ISSUE THREAD

**Issue by LeRouxVanWyk** [mattpass/ICEcoder#585]
Possible to create functionality where you have a sideview containing a list of classes/functions within a file, that you can click on to jump to them within the file.

**Comment by mattpass** [comment]
Sounds good - to be done at some point soon.

**Comment by mattpass** [comment]
Really like this idea. I'd love to introduce a minimap on the side with perhaps tabs to switch between class/function list and the minimap view. Hoping to get this within the v5.4 release.

**Comment by DarkoSvitic** [comment]
I wanted to finish this but I can't even add this to ICEcoder...But here it is.
It lists all ids / classes in current file.

function cssSitemap() {
    var allTags = document.body.getElementsByTagName('*');

    var ids = [];
    for (var tg = 0; tg< allTags.length; tg++) {
        var tag = allTags[tg];
        if (tag.id) {
                ids.push(tag.id);
         }   
    }

    ids.forEach(function(entry) {
        var div = document.getElementById('cssSitemap');
        var li = document.createElement("li");
        var text = document.createTextNode(entry);
        li.appendChild(text);
        div.appendChild(li);
    });

    var classNames = {};
    for (var tg = 0; tg< allTags.length; tg++) {
        var tag = allTags[tg];
        if (tag.className) {
          var classes = tag.className.split(" ");
        for (var cn = 0; cn < classes.length; cn++){
          var cName = classes[cn];
          if (! classNames[cName]) {
            classNames[cName] = true;
          }
        }
        }   
    }
    var classList = [];
    for (var name in classNames) classList.push(name);

    classList.forEach(function(entry) {
        var div = document.getElementById('cssSitemap');
        var li = document.createElement("li");
        var text = document.createTextNode(entry);
        li.appendChild(text);
        div.appendChild(li);
    });
}

**Comment by mattpass** [comment]
Think you have the wrong idea here. The idea is to generate a list of class or function names that are shown in say a PHP file. If a file you're editing contains ```class myGreatClass { blah... }``` and ```function superFunc() { blah... }``` then a list in the top right corner would show 2 names - myGreatClass and superFunc. You could click on these to jump quickly to the place in the file where they're defined.

**Comment by mattpass** [comment]
As a very basic start - within lib/ice-coder.js in the cMonChange function set ```var cM = top.ICEcoder.getcMInstance(); var content = cM.getValue()```. Now content contains the text within the document on every keypress. You'd need to scan through this looking for the words 'class' or 'function'. Upon finding one, add it to your array list and also note the line number. When finished scanning through, show the list which shows the names you picked up and when clicked on, will go to the relevant line number in the file.

**Comment by mattpass** [comment]
OK, minimap well underway, but function/class browser now finished. Works great and so closing issue.
