### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#587]
A couple of people have asked about version control of files and while we have the ZipIt! plugin, it backs up an entire dir on an interval and GitHub integration, it involves a few clicks of switching into that mode, committing, pushing etc. There's no simple, local version control.

Adding a couple of lines to /processes/on-file-save.php will save the file with a timestamp in the /backups dir:
```
$pathParts = pathinfo($fileName);
copy($docRoot.$fileLoc."/".$fileName, "../backups/".$pathParts['filename']."-".time().".".$pathParts['extension']);
```

However, this simple 2 line solution doesn't include a dir structure or any simple way to get back to an older version of a file, plus you need to know it's saved there.

Would suggest expanding on this 2 line solution to include dir structure also within the backups dir. Then right clicking on a file, you could access a new option - 'Version Control' which would show a list of all saved backups (ordering by filename would put this into timestamp order and allow us to display as version 1, version 2 and so on).

The user would need choices on what to do next from the Version Control screen:

```
Version 1      Open in new tab      Open in diff mode      Restore as new version
Version 2      Open in new tab      Open in diff mode      Restore as new version
Version 3      Open in new tab      Open in diff mode      Restore as new version
Version 4      Open in new tab      Open in diff mode      Restore as new version
```

Open in new tab will open it in a new tab. Open in diff mode will open current version in left pane and that older version in the right pane. Restore as new version would move the current version to the /backups dir as Version 5 and copy the older version chosen over to the live dir as well as copying it as version 6 in the /backups dir so live and the latest backup are in sync.

**Comment by mattpass** [comment]
To help users know 'X versions' are available, indicate this next to the broken tag indicator. So, if there are 5 saved versions, it would display '4 older versions available'. Clicking this shows the version Control screen for the current file/tab.

**Comment by mattpass** [comment]
Need an option to turn version control backups on/off from the settings screen as not everyone will want backups as they could eat up disk space. Setting should be on by default?

**Comment by webguide** [comment]
First of all thank you for your active interest in my proposal. Well, maybe not everyone is happy for extra space required by backup, so I believe it should be activated manually. Another possibility should be put it inside a daily folder, so that it does not grow without any control. Eg. backup/2015/0904/(path)/filename.php
But another question about this interesting backup is: does it work also for ftp savings? If yes, in that case, is there a unique prefix for path? It is necessary that it is NOT the host (which can be the same for different websites).

**Comment by mattpass** [comment]
Indeed. Am undecided on whether it should be on/off, but can go with overall user preference if more people have an opinion on default.

The dated dirs idea is a a good one, will have a think about that also. It does mean simpler (non timestamped) filenames can be stored and you can remove old dirs from previous dates. Maybe even a setting could be introduced to 'Remove backups older than [14   ] days' perhaps.

Yes, the backup would work for FTP also. The 2 line example above doesn't right now (that works for local only), but I can make this work in a different way so it handles local files or files over FTP. Eitherway, will still store a copy in ICEcoders /backups dir. Would suggest storing under sitename and path (as you say. host can support many sites so not realiable).

**Comment by mattpass** [comment]
Maybe the dir structure inside /backups should be:

```
/backups/local/2015/Sep-04/xyz/sub/abc.php        <<< for local saved file
/backups/mysite.com/2015/Sep-04/xyz/sub/abc.php   <<< for FTP saved file
```

**Comment by webguide** [comment]
Great!

**Comment by mattpass** [comment]
OK, will need to give me a short while (few weeks?) to make this available, but think it's a feature a lot of people would like.

Am actually tempted to redo delete also so rather than actually remove the file, it moves it to backups. Deleting files at the moment is real deletion and the file is gone. Maybe moving it to backups is better, non destructive solution.

**Comment by webguide** [comment]
IMHO it's a good idea, and even if you will never know that, there will be many moments in the world when a developer will thank you for allowing him not to lose his work. Common users love the trash can, but even developers are happy when they do not lose hours or days of coding...

**Comment by mattpass** [comment]
Made an initial start on this, so upon saving it'll now store the file in the backups dir (within a host > year > month-day structure as detailed above, creating dirs. where they don't exist). Also stores by filename but if that exists, with add the next free incremental number at the end in parens.

Tried this and works great with FTP too, example file saved may say be...
```
/backups/demo.icecoder.net/2015/Sep-05/index.php (3)
```
...for the 3rd save that day.

**Comment by mattpass** [comment]
Probably only about 20% done overall here. Next steps are to save the dir structure the file resides within (as per ```xyz/sub/``` above). Then need to add a couple of settings to turn this backup system on/off (still not sure what should be default tho!), plus how many days to keep (eg 14). Will allow these 2 controls to be set from within settings. Think we'll be 50% done then and the 2nd half of this will be showing the version control screen, with all available backups in order and allow user to click the 3 choices mentioned.

**Comment by mattpass** [comment]
Now using file structure:
```
/backups/demo.icecoder.net/Sep-07-2015/xyz/sub/index.php (3)
```
(Note year moved into dated dir to involve 1 less dir level, plus sub-dirs to file included and only creates dirs if the full path doesn't exist, meaning better efficiency and fewer checks).

**Comment by webguide** [comment]
Well, if I can tell you mine, I thinked of the year folder for the case one leaves it without realising during years, but you are right, it should be too much... But, IMHO, it should be important to keep alphabetical order equal to date order, so if the folder structure should be similar to the ISO date (2015-09-07) I believe it should be more usable. Do you agree?

**Comment by mattpass** [comment]
Yeah, was almost going to go with ISO. Only reason I didn't was because people in different countries may think 2015-09-07 is actually yyyy-dd-mm instead of yyyy-mm-dd. Still, I think ISO is infact better so can switch to that. It should be a rare case that users have to look in backups folder anyway, as the version control UI I'll build will handle things. Anyway, will go with your suggestion as it's better. :-)

**Comment by webguide** [comment]
Thank you, I am very happy you appreciate my suggestions. An authentic dev-to-dev exchange of ideas.

**Comment by mattpass** [comment]
Of course, happy to hear ideas and implement them if better than my ideas. :+1: 

More coming over next couple of days - settings to turn off/on and only keep XX days of backups...

**Comment by webguide** [comment]
News? I'd be very happy to buy the code, but I need to do it safely, so I need backup reliability

**Comment by mattpass** [comment]
Have done a good few things over the last week - backups being stored in the /backups dir under host name and datetime, plus incremental too. Settings added to setting screen to turn backups on/off and choose how to long to keep them for (14 days as default) and clears backups dirs older than this.

At the moment I've almost finished a display at the bottom of ICEcoder, that shows the number of backups it has for a file and as you save, it increments by 1.

So it's already saving backups which I think solves the immediate concern. Within the next few days I'll set up an interface to show those as a list you can then do something with (details in the https://github.com/mattpass/ICEcoder/issues/587#issue-104846312). :-)

In short - 75% done so far.

**Comment by mattpass** [comment]
Feel free to grab the latest version from GitHub BTW and you can see as you save, it puts a copy in the /backups dir also.

**Comment by webguide** [comment]
Sorry but the latest downloadable version appears to be 5.2, even without ftp support. How can I doto download the updated version?

**Comment by mattpass** [comment]
The updated version (items added after v5.2) can be obtained from this GitHub repo. If you're not sure how to get it, go to this URL and click Download Zip: https://github.com/mattpass/icecoder.

**Comment by mattpass** [comment]
Added some extra code to now show the number of backups so only need to tackle showing the list and letting you restore them in some way.

Something that occurred to me is that if you move a file, it will lose path reference for it and you'll start again from 0 versions. If you also delete the file, there is no UI planned to get to version controlled backups as you need to open a file to see the backup counter, which will ultimately be clickable to view the list of backups you can restore from.

**Comment by mattpass** [comment]
Also worth noting is that the backups count isn't realtime/live info. So if the backups are removed (either manually or in a cleanup, the counts will be wrong).

**Comment by mattpass** [comment]
Working on a nicer UI than the one proposed at the start of this issue. To the left will be a list of all backups. When you click on any of them, it shows the file in a preview pane. Will also provide file property details including modified datetime and size, plus the 3 links mentioned to open in new tab, open in diff mode and restore as new version.

This will allow for much easier, quick viewing of old versions, info on the file and actions on what to do with the file should you want to retrieve it in some way.

About 90% done on this whole solution now and to be committed v soon.

**Comment by webguide** [comment]
Great!
FTP and versioning are fundamental!
Thank you!

*Aldo Medri*
---------------
Please consider the environment before printing emails

2015-10-09 10:20 GMT+02:00 Matt Pass <notifications@github.com>:

**Comment by mattpass** [comment]
Need to redo/improve the code within lib/backup-versions.php (code tidy up, plus use chosen theme, vis tabs, indent size etc as per settings screen). Also need to take into account the mode we should be using. It's however displaying the content OK and this is fine as a start point.

**Comment by mattpass** [comment]
All done as described, aside from a few improvements that could be made, which I'll note in a separate issue. Closing this as largely completed tho.
