### ISSUE TITLE
Can't open file with symbol + in the name

### ISSUE THREAD

**Issue by LordKBX** [mattpass/ICEcoder#595]
I've only obtain an error message like the file don't exist

**Comment by mattpass** [comment]
I will check this out, thanks.

**Comment by mattpass** [comment]
Yes, this is an issue, will look to fix.

**Comment by mattpass** [comment]
Sorry for the delay, but back on ICEcoder improvements again and covered this. Done and closing.

**Comment by mattpass** [comment]
Leave a comment

**Comment by LordKBX** [comment]
Thanks
