### ISSUE TITLE
Question about Subdomain

### ISSUE THREAD

**Issue by iLtc** [mattpass/ICEcoder#599]
Hi!

I have three applications on my server, and the folder structure looks like:

```
~/webapps/app1
~/webapps/app2
~/webapps/app3
~/webapps/ICEcoder
```

I want to use ICEcoder to edit all of the applications, but I do not have permission to point a subdomain to ```~/webapps/```, I can only point the subdomain directly to ```~/webapps/ICEcoder```. But if I do so, when I visit the subdomain, I can only see the ICEcoder's files.

So, except copy ICEcoder to each application's folders, what can I do?

**Comment by mattpass** [comment]
You could create a symlink folder 'ICEcoder' in each app folder to it? That should work fine.

**Comment by iLtc** [comment]
Thanks for your help!

I created a symlink folder 'ICEcoder' in app folder. But when I visit ```http://domain.com/ICEcoder```, it redirects to ```http://domain.com/ICEcoder/settings.php``` and throw me a 404 error.

I cannot find ```settings.php``` in folder ```ICEcoder```, do I have to create one?

**Comment by mattpass** [comment]
Mmm no, settings.php is in the lib folder and sounds like it's not picking up the path correctly. I will try the same setup and let you know if I find a bug to fix.

**Comment by iLtc** [comment]
I didn't know why, but when I removed all of the files and reinstalled 'ICEcoder', it worked. Now I can use 'ICEcoder' in 3 different folder.

Thank you for your help again!

**Comment by mattpass** [comment]
No problem and glad it's working OK for you now.
