### ISSUE TITLE
Keep long folder / file names on ONE line

### ISSUE THREAD

**Issue by cedricgeffroy** [mattpass/ICEcoder#600]
Hello, 

how can I keep the name of a long folder (or file) on ONE line. To avoid this kind of display ?
I tried with CSS but it's not easy to find ...

Thank you

![image](https://cloud.githubusercontent.com/assets/4662905/11195254/1304ea1a-8c7f-11e5-98c3-97cdebfa784e.png)

**Comment by mattpass** [comment]
It likely needs 'white-space: nowrap' applied to the CSS class for it. Will add that as I think it'd be a good tweak.

**Comment by mattpass** [comment]
OK, added to ```.fileManager ul, .fileManager li``` in lib/file-types.css to resolve this issue. Done and closing.
