### ISSUE TITLE
Unable to open css files > freeze

### ISSUE THREAD

**Issue by cedricgeffroy** [mattpass/ICEcoder#601]
I can open php files but not css files.
I have the small white popup on left bottom with "Opening xxxxxx.css" and then icecoder freezes.

Then I have to reload the page and to login again.

Any ideas? 
Thank you.

**Comment by mattpass** [comment]
Don't think it's specifically unable to open a CSS file and instead losing 'session' logged in state (as you're booted out on reload and need to login again).

Can you confirm that pls?

**Comment by cedricgeffroy** [comment]
Ice coder working perfectly, I can edit and work on php files, but as soon as I try to open a css file, I can't do anything else and I have to reload the page and then to login again...
Is it clear enough ?

**Comment by cedricgeffroy** [comment]
No errors :(

**Comment by mattpass** [comment]
Mmm OK. Maybe try opening lib/config-settings.php in ICEcoder and change the value next for fileDirResOutput from ```"none"``` to "both"```.

With the Console tab showing reload ICEcoder and try to open a CSS file. It should output data in the console about what it's doing. Maybe something there looks wrong?

**Comment by cedricgeffroy** [comment]
Nope still nothing... 
I installed a new one in another directory / domain of my server.
Everything is working well now. 
Let's forget it :)

Thank you for your help anyway.
And GREAT tool ;)

**Comment by mattpass** [comment]
OK well glad it's working fine elsewhere. If you ever find out what the issue was and it's something I can fix let me know. :-)

Closing this otherwise.

**Comment by cedricgeffroy** [comment]
Damn ! I have again the issue with the new installation and didn't change a thing in the configuration...
I tried from firefox too and same problem...

**Comment by cedricgeffroy** [comment]
I tried to install a clean version in the same directory and still have the issue.
Last time in this directory it worked... 
I'm trying to find why it worked and now doesn't work anymore...

**Comment by cedricgeffroy** [comment]
Tried with 755,757,775 on directories : backup, lib, plugins....
Tried with commenting line 20>35 in lib/settings-common.php

**Comment by mattpass** [comment]
Any luck in the last few days? It's weird that it was working and now not. So the only problem is that you can't open CSS files? Everything else works perfectly? Really I don't understand why, ICEcoder doesn't treat CSS files any differently and loads them as a text file just like others (.php, .js, .html etc)

Maybe check your PHP error logs after trying to open a CSS file for clues?

**Comment by mattpass** [comment]
Made some improvements to saving which may also help here. Closing.
