### ISSUE TITLE
install adminer

### ISSUE THREAD

**Issue by dkurzke** [mattpass/ICEcoder#603]
if i want to install adminer there is only a transparent frame with white shadow. nothing happens. whats wrong? a problem with directory permissions?

**Comment by mattpass** [comment]
If you've clicked the link to show the plugins panel, it sounds like fopen isn't enabled on your server. fopen needs to be enabled to get the list of plugins to show (and install them after). Maybe check that?

**Comment by dkurzke** [comment]
i see the list of plugins and i clicked the adminer install button. the next panel is empty.

**Comment by mattpass** [comment]
That's strange. If you press CTRL+A to select everything on the page, does it reveal any hidden text (black text on a dark background, revealed by highlighting it)?

It's sounding like maybe you don't have suitable write permissions on dirs, as you first suspected. Maybe check the permissions on ICEcoders 'plugins' and 'tmp' dir. (When you click to install a plugin, it stores the plugin zip in the 'tmp' dir and then unzips it into a new dir inside the 'plugins' dir.

Hope that helps?

**Comment by dkurzke** [comment]
![adminer](https://cloud.githubusercontent.com/assets/15921645/11293082/aad42f8e-8f56-11e5-9695-700718d1365a.JPG)
OK. "tmp" and "plugins" are now 777 and there is a ZIP in tmp. One problem solved. Not more. All other dirs are 710 and the files are 740. The install frame is still blank. Maybe the next problem is the ZIP stream? But why is the frame blank?

**Comment by mattpass** [comment]
I would suggest removing the zip file and when you click the link to open the plugins display, is it still blank? Hopefully you see the list and when you click Install, it then shows a blank screen. If this is the case, I would suggest finding out if your server has both fopen and zip capabilities enabled.

(To find this out quickly, make a PHP file that simply contains ```<?php phpinfo();?>``` and view that. It will show all PHP settings info and you can find on page 'fopen' and 'zip' text and checkout your settings).

fopen is needed to view the plugins list and download, as you can see the list and it downloads a zip, I suspect this isn't the problem. Maybe zip isn't enabled in php.ini?

**Comment by mattpass** [comment]
Heard nothing back on this and think it's a server thing for you, so closing.
