### ISSUE TITLE
Text Highlighting

### ISSUE THREAD

**Issue by LeRouxVanWyk** [mattpass/ICEcoder#609]
When selecting text in the code editor using the mouse, a horizontal movement causes the left menu to increase/decrease in size.

**Comment by mattpass** [comment]
This would be because you grabbed the rightmost edge of the file manager pane? Can select text in the editor pane just fine I believe?

**Comment by mduffor** [comment]
I have this issue as well.
  * Drag the right edge of the file manager pane and drag it to the right
to its maximum size.
  * Left click in the editor pane, and slowly move your cursor to the left.
  * As you pass over the dividing line between the editor window and the
file manager, the dragging of the pane divider will activate and start
resizing the two windows.

It will also start to select a rectangle of text in the file manager pane,
but that's more of a cosmetic issue.

Cheers!

**Comment by mattpass** [comment]
Ah thanks for confirming. Sounds like it's getting stuck in 'drag the width of file manager' mode. Will look into it!

**Comment by mattpass** [comment]
OK, made some improvements so selecting text in the editor pane won't begin dragging the file managers width or draw a selection box in it, if you move the mouse leftwards. Done and closing.
