### ISSUE TITLE
Cannot access ICEcoder via domain name / IP address (localhost address only)

### ISSUE THREAD

**Issue by bfishman** [mattpass/ICEcoder#622]
After upgrading to 5.4 (although this happened during 5.2 -> 5.3 as well), accessing ICEcoder from outside of my local network results in the following:
```
Not Found

The requested URL /ICEcoder/settings.php was not found on this server.
```

Strangely enough, the same error occurs if i visit `<external ip address>/ICEcoder` or `<mydomain>/ICEcoder` _from the hosting computer._  But visiting `localhost/ICEcoder` on that computer works perfectly fine, bringing up the application. My server is accessible from the internet, and static webpages are served just fine.

This seemed like an Apache config issue to me, but I poked around in settings to find where the failure was occurring. See the following code from settings.php:

```
// On mismatch of settings file to system, rename to .old and reload
If ($ICEcoderUserSettings["versionNo"] != $ICEcoderSettings["versionNo"]) {
        //die("__FILE__ : ".__FILE__."<br>dirname: ".dirname(__FILE__)."<br>settingsFile: ".$settingsFile);
        rename(dirname(__FILE__)."/".$settingsFile,dirname(__FILE__)."/".str_replace(".php",".old",$settingsFile));
        //die("this is reached");
        header("Location: settings.php");
        //die("this is not reached");
        echo "<script>window.location='settings.php';</script>";
        die('Found old settings file, reloading...');
}
```

The top (commented) `die` prints:

```
__FILE__ : /home/<username>/webroot/ICEcoder/lib/settings.php
dirname: /home/<username>/webroot/ICEcoder/lib
settingsFile: config-mydomain_com.php
```

The second `die` is reached, but the third is not. So the `header()` function is somehow failing.

After a bit more digging, the contents of `$ICEcoderUserSettings`, prior to the above code is:

`Array ( [previousFiles] => [configCreateDate] => 1459222891 )`

Thus it's missing any 'versionNo' field.  So I commented out the entire settings mismatch block above, allowing the settings.php file to continue, and the next failure occurred at:

```
// Determin our allowed IP addresses
$allowedIP = false;
for($i=0;$i<count($_SESSION['allowedIPs']);$i++) {
        if ($_SESSION['allowedIPs'][$i]==$_SERVER["REMOTE_ADDR"]||$_SESSION['allowedIPs'][$i]=="*") {
                $allowedIP = true;
        }
}
```

..With the error `die('Sorry, access not permitted');`. I believe this is because the $ICEcoder array does not contain any 'allowedIPs' --- even though the `config___users-template.php` file specifies an array with "*" as that field's value.

**Note:** while poking around (having removed all the debugging `die()`s, it seems that while `config-localhost.php` is fully-formed file, any of the other files, such as `config-127.0.0.1.php` are all empty and read-only. Could that be relevant?

**Comment by mattpass** [comment]
Hey @bfishman. Reading through all of this, I'd say yes, your last comment is probably along the right lines of where the error lies. There should only be config-[DOMAIN/IP].php files for domains/IPs you've accessed it under and both should be fully formed files.

Establishing the correct config filename to use in a consistent way is likely the issue overall. Establishing that and loading data from the file it thinks it should be using is done between:
https://github.com/mattpass/ICEcoder/blob/master/lib/settings.php#L17-L54

I think the issue is here where it's using ```$_SERVER['SERVER_NAME']```. Maybe you could just try changing that to ```"TEST"``` and see if it creates a config-TEST.php file file and resolves your issue?

**Comment by mattpass** [comment]
(The suspected issue line where you could make that TEST change is line 40 of lib/settings.php BTW) :-) Let me know how you get on.

**Comment by mattpass** [comment]
The reason I suspect this is because you say the contents of ``` $ICEcoderUserSettings``` is only ```Array ( [previousFiles] => [configCreateDate] => 1459222891 )```. These 2 items are tacked on later in lib/setttings.php after loading the data from your settings file on line 54. These 2 items should be added into an array of 20+ items loaded from your config file to have a full array of info it needs to run.

Something I just noticed from your info above is that you have a ```config-127.0.0.1.php``` file. When I access ICEcoder under 127.0.0.1 locally it works fine and creates a ```config-127_0_0_1.php``` as I'd expect. It should be replacing dots with underscores also on line 40 of ```lib/settings.php```. Is it not doing that for you?

**Comment by bfishman** [comment]
Will look into this tonight when home. Also, very possible it's actually `config-127_0_0_1.php`.

**Comment by bfishman** [comment]
@mattpass Interesting. From the hosting computer, I launched the following:

```
localhost/ICEcoder
127.0.0.1/ICEcoder
192.168.1.22/ICEcoder       <--------------- my internal ip
sourcedreams.com/ICEcoder  <-------------- domain redirects to this host
```
but the only config files in my `lib` folder are:
![image](https://cloud.githubusercontent.com/assets/3529531/14230786/5616400e-f923-11e5-8029-1c7dd62e1daa.png)

Will poke around in the code where you suggested..

**Comment by bfishman** [comment]
Okay, just changed this line:
`$settingsFile = 'config-'.$username.str_replace(".","_",str_replace("www.","",$_SERVER['SERVER_NAME'])).'.php';`

to this:
`$settingsFile = 'config-'.$username.str_replace(".","_",str_replace("www.","","TEST")).'.php';`

I got the same error as before, and here's the contents of my lib dir:
![image](https://cloud.githubusercontent.com/assets/3529531/14230798/2097528c-f924-11e5-9ac1-4a3aa5987d56.png)

No `config-TEST.php`, but instead a `config-TEST.old` file (as with the other domains).

**Comment by bfishman** [comment]
(whoops, closed by accident)

**Comment by bfishman** [comment]
Help me understand something? In the following block:
```
// Create user settings file if it doesn't exist
if (!file_exists(dirname(__FILE__)."/".$settingsFile) && $ICEcoderSettings['enableRegistration']) {
        if (!copy(dirname(__FILE__)."/".$configUsersTemplate, dirname(__FILE__)."/".$settingsFile)) {
                die("Couldn't create $settingsFile. Maybe you need write permissions on the lib folder?");
        }
        $setPWorLogin = "set password";
}
```

if `enableRegistration == false`, and `dirname(__FILE__)."/".$settingsFile` does *not* exist, when is it ever made? This seems to be happening for me. `$settingsFile` does not exist, and thus `include(dirname(__FILE__)."/".$settingsFile);` loads nothing. Hence `$ICEcoderUserSettings["versionNo"]` is undefined.

**Comment by mattpass** [comment]
Hi @bfishman - seems weird you're ending up with so many different ```config-...``` files, maybe down to the redirects? I'd expect a fixed value like 'TEST' to work tho as it's not trying to determine anything. If you delete anything starting ```config-``` (config followed by hypen), close all browser windows and boot up again - do you get multiple ```config-...``` files created?

**Comment by mattpass** [comment]
Re the block of code above - correct - if ```enableRegistration``` is ```false```, no new config file is created. It must be set to ```true``` if you want to allow new accounts to be created and ```false``` when you don't want to allow new ones to be created. If you have it set to ```false``` you can only log into previously created config accounts.

So if you have this set to ```false``` in your ```lib/config___settings.php``` file, it'd definitely be a reason new config files (eg for TEST as per your experiment) aren't created.

Hopefully you found the cause here? Let me know?

**Comment by bfishman** [comment]
Bad news. Due to an unrelated issue, I ended up having to reinstall my linux VM yesterday. 

I just finished reinstalling my stack and now cannot reproduce this problem (not that I wanted to!). So hopefully that means it was just an Apache configuration error.  Sorry :/

**Comment by mattpass** [comment]
No problems at all. If everything is fine afterall then I'll close the issue. Let me know if any other troubles. :-)

**Comment by bfishman** [comment]
I may have found a solution to the problem, but can't test it under the exact same circumstances to be certain. I did receive the same error again. This happened after I disabled 'registration' mode - using the settings gui I first enabled multi-user, then disabled registration, then disabled multi-user.

After that was done, addresses through which I had already logged on, such as localhost and my domain name, worked as expected. But then I attempted to connect to the raw external IP address of my domain - one I had not yet connected with. This caused the error I was having before.

I then re-enabled registration, logged in via the raw external IP address, set my password, and then disabled registration. Finally, I attempted to connect again and the error message was gone.

Why did I disable registration in the first place?  I may be wrong, but it seems that in single-user mode with registration enabled (the default), any login attempt to a new address for the first time (ie localhost vs 127.0.0.1) *will allow the use to set their own password*. This seems like a gaping security hole. Please verify.

Note: all ICEcoder sessions must be closed during editing of the settings GUI for the change to persist.

**Comment by mattpass** [comment]
Wow, I think you're spot on with all of that and it may well be a security issue there. Think ICEcoder is doing everything correctly but could also consider the initial password as 'set' the first time if it's been set on the domain or IP.

Mmmm, it's a tricky one because it's doing what it should but could be more helpful in covering a potential issue here.

**Comment by mattpass** [comment]
The only good solution I can think of here is to create a duplicate, IP based config file also on first password setup, if it doesn't exist yet. Will do that as a short term measure unless there is a better solution.

**Comment by mattpass** [comment]
OK, implemented that solution and seems to work fine: https://github.com/mattpass/ICEcoder/commit/838612932cdc57b17ee7200574c22e4d575ba1e3

If you have time to check it over and raise any issues that'd be appreciated. :-)

**Comment by mattpass** [comment]
If I now visit the domain name, set a password, logout, close all browser windows. Go to IP address and if your server setup enables you to access ICEcoder you'll now get a login screen (a good example is localhost vs 127.0.0.1).

**Comment by bfishman** [comment]
Matt, awesome! I'm traveling today so can't test out your fix right away, but it sounds like you found a good solution. I'm not sure this will cover the following case, however:

-User installs ICECoder, connects via localhost for first time and sets password.
-User assumes site is password protected. Never attempts to access site via external IP/domain
-Intruder connects to the host via external IP and/or domain, sets own password, and has access to the site.

If that's indeed the case, then I recommend using a global config file that is username-based, not Server address-bssed -- even in 'single user' mode. ie instead of config-localhost.php, config-external_IP.php, etc, you would just have a single file: bfishman.php for example.

Then, after the first user name has been registered and passworded, automatically disable further registration unless explicitly enabled.

Hope that makes sense. Great work Matt, ICEcoser rocks.

**Comment by mattpass** [comment]
Mmm I see your thinking but this would cause issues where there is 1 install of ICEcoder and say 5 domains with a symlink on an 'editor' dir in each of them to the ICEcoder dir. So 1 dir really and there would be 5 config files, one for each of the domains.

**Comment by mattpass** [comment]
Think you may have come up with the solution tho re enable registration.

On accessing ICEcoder for the first time it could show a 'Disable further registrations' checkbox which is ticked by default. So when you register for the first time it also switches enableRegistration from true to false. Now no matter what domain or IP you try to login under you won't be able to set a password.

**Comment by concept-core** [comment]
I am not sure how the password is saved but maybe think about using a sqlite file to save the user.

**Comment by mattpass** [comment]
The password is encrypted and saved in the config file related to the user. I've considered using SQL Lite or similar before but due to size of lib and for not too much benefit, plus hassle for users to set up and manage decided it's not worth it.

**Comment by bfishman** [comment]
I like your 'disable further registrations checkbox'. I'd recommend putting a sentence in the readme and on your website mentioning it treats different addresses separately, so registration must be repeated for each.

I suppose an alternative could be to separate user registration and website configuration, then have an administrative user accoubt that could assign other users to various sites. But this seems like a lot more work.

**Comment by mattpass** [comment]
OK, checkbox added to login page and is checked by default, so first setting of password and this option checked will mean it switches true to false and no one can register then under any domain/IP, unless the original user logs in, goes to Edit > Settings and enables this option. Done and closing, thanks for your help @bfishman :-)
