### ISSUE TITLE
bug in saving

### ISSUE THREAD

**Issue by anagnam** [mattpass/ICEcoder#628]
hitting CTRL+S does not guarantee that the file is always saved. Sometimes it work, sometimes and more often than not, it doesn't save. So I wish theres an actual "Save" button so I can force to manually save the file instead of hitting CTRL+S.
For now, if CTRL+S doesn't work, I would have to refresh ICEcoder a couple of times just to make it work.

**Comment by mattpass** [comment]
There's no force save mechanism I can really use. There have been some improvements implemented today re this. Can you grab the latest version from this repo and confirm if all is OK now?

**Comment by anagnam** [comment]
Ive used the auto-update feature and the upgrade was successful so I assume I have the latest version. But still Im experiencing the same problems I mentioned above.

**Comment by mattpass** [comment]
No, updating will get the latest official release (v5.4) from the website. You'd need to get the files from GitHub for the very latest code after that.

**Comment by mattpass** [comment]
Think all is OK with the very latest release. When you have your server sessions working and can test, if you have any further save issues let me know. Should be fine now tho so closing this. Please reopen if not.
