### ISSUE TITLE
Permission 755 and Italian language problem

### ISSUE THREAD

**Issue by jacklocke** [mattpass/ICEcoder#629]
Loaded on server.

set php.ini with zipArchive activated.

I have to keep permission 755 to make it work on this server.

but when I put language to Italian, no one file can be opened.

If I return on English language, all works fine

**Comment by mattpass** [comment]
Mmmm @jacklocke - must be something is missing in the Italian language file. (see 'lang' dir in ICEcoder). I want to get these files overhauled (basically lang/italian.php and many other languages need to be updated to everythiung lang/english.php contains). Probably something missing.

There's an issue for this #446 but need various people from around the world to help. ICEcoder *should* however use English text pieces where Italian isn't available, as a fallback. Let me look into that.

**Comment by mattpass** [comment]
Ah OK, found the issue - the Italian language has a few items with apostrophes such as ```C'è stato un problema tecnico....` which needs a backslash prior to the apostrophe to unescape things - eg ```C\'è stato...```. This should resolve the issue but if you have any more problems please let me know. Closing.
