### ISSUE TITLE
Unable to create new file or open existing file since upgrading to 5.4

### ISSUE THREAD

**Issue by dancramp** [mattpass/ICEcoder#634]
Hi,

Icecoder was working fine on version 5.3 (it's brilliant by the way, my favourite IDE!). I've upgraded and now can't open or create anything. Any ideas greatly appreciated!

I'm getting the following error:

ice-coder.min.js?microtime=1461183274.8827:115
 POST ICEcoder/lib/file-control-xhr.php?action=save&fileMDT=u…ileVersion=undefined&saveType=saveAs&csrf=572cecda8483b25eda79820a6f2c35b1 500 (Internal Server Error)
ICEcoder.serverQueue @ ice-coder.min.js?microtime=1461183274.8827:115
ICEcoder.saveFile @ ice-coder.min.js?microtime=1461183274.8827:59
onclick @ (index):155
ice-coder.min.js?microtime=1461183274.8827:114 ICEcoder error info for your request...
ice-coder.min.js?microtime=1461183274.8827:114 undefined

Thanks.

**Comment by dancramp** [comment]
Hi,

Just upgraded to 5.5 and issue is resolved - I can open and save with no issues.

Cheers!

**Comment by mattpass** [comment]
Excellent - glad to hear it. :-)
