### ISSUE TITLE
Github commit not working

### ISSUE THREAD

**Issue by zepatrik** [mattpass/ICEcoder#657]
There is some issue with the github integration. When trying to commit there is immediatly this output to the JavaScript console:

``` JavaScript
github.php?action=commit&selectedFiles=|web-tutorial|tutorial.css&csrf=add4967……:21

Uncaught ReferenceError: commitFiles is not defined
```

The commit is not working at all (obviously).

**Comment by mattpass** [comment]
That's strange - seems like the file isn't fully loaded. I did notice that both a username and email address need to be provided in all commits now and added some extra params re that.

I'll close the issue assuming that fixes it (or it's generally OK for you now). Please reopen if not, thanks.
