### ISSUE TITLE
When https://icecoder.net is down : login to MY icecoder is VERY slow or timed out

### ISSUE THREAD

**Issue by cedricgeffroy** [mattpass/ICEcoder#658]
Hello,

Currently https://icecoder.net is down and it looks like that when the ICEcoder website is down it's very difficult to login to my icecoder, hosted on my server.

**Comment by mattpass** [comment]
Mmmm that's weird - I've not detected any downtime. However, you do raise a very good point - it tries to detect a newer version for up to 30 secs over CURL. Should probably shorten that.

**Comment by mattpass** [comment]
Have shortened checking for version number on load of ICEcoder to 5 secs now.
