### ISSUE TITLE
error trying to edit  self closing html tag

### ISSUE THREAD

**Issue by malmestig** [mattpass/ICEcoder#659]
hello,
first thanks for this great piece of software.
 
When I try to edit this html
`<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Righteous"/>`
nothing happens and in the console I get

10:27:58.414 TypeError: e[f] is null
ICEcoder.cMonBeforeChange()ice-coder.min.js:20
createNewCMInstance/<()editor.php:221
x.signal()codemirror-compressed.js:49
jd()codemirror-compressed.js:46
kd()codemirror-compressed.js:46
xa()codemirror-compressed.js:45
Ca.prototype<.poll/<()codemirror-compressed.js:48
fc()codemirror-compressed.js:46
Ca.prototype<.poll()codemirror-compressed.js:48
Ca.prototype<.init/<()codemirror-compressed.js:48
1ice-coder.min.js:20:468

I'm using Firefox. 
other tags seem to work fine.

**Comment by zepatrik** [comment]
I encounter the same problem, happening with every self closing tag in every browser

**Comment by mattpass** [comment]
Thanks for the info - found the issue quickly and pushed a commit to fix this issue. :-)
