### ISSUE TITLE
Version 5.7 - wrong indent after clean line

### ISSUE THREAD

**Issue by moudsen** [mattpass/ICEcoder#671]
```
<?php<enter>
<tab># This is a comment<enter>
<cursor jumps way beyond first set tab (+4 tabs to be exact)>
```
But this also happens wit other statements

I'm using 5.7 latest version taken from GitHub

**Comment by moudsen** [comment]
Seems to happen only on a new line at the first indent position

<tab>if (statement) {

works (correctly to 2nd indent)

<tab>{<enter>

works (correctly to 2nd indent)

**Comment by mattpass** [comment]
Yes, this isn't correct - will look into it.

**Comment by mattpass** [comment]
Actually, I've looked into this and seems fine? Can you let me know if you see the same issue at: http://codemirror.net/mode/php/index.html and also if you've changed your settings from indent with tabs/spaces and the unit size?

**Comment by mattpass** [comment]
Going to close this, please reopen if still a problem.
