### ISSUE TITLE
When going into donate process the system trips a firewall alert.

### ISSUE THREAD

**Issue by sfitzjava** [mattpass/ICEcoder#677]
Background: My service provider does a great job at securing the sites from malicious software and hacking threats, one of their techniques blocks domains when strange IP activity happens from the servers.

Process: 
    1) login to the system and get the dashboard page.  
    2) select "unlock" under trial version time
    3) get to page with 'donate' and code input fields
    4) select 'donate'  and get sent to external page on ICEcoder site
    5) -- At this point the firewall trap is set-off and my website is blocked --

I went through this process three times and each time with the same result.  
The first time I was doing other things and did not connect it.
The second time I was only doing this donate request and thought there might be something.
The third time I am sure that is what triggered the issue.

There needs to be a disclaimer as to what your code is doing at this point (outbound message to your servers, transmission of data?  I don't know what is being attempted, but I am not a fan of people putting beacon-ware on my server that could allow them to gain access to my system WITHOUT my permission or knowledge... And then to expect me to pay them to do so?!  not cool!)

Please either disclose what you are doing... OR BETTER YET, don't do it.

Information from error-log.txt
  Undefined offset: 0 in /<installedDir>/lib/file-control-xhr.php on line 76

**Comment by mattpass** [comment]
Hi there. We're not doing anything bad that you mention above? When you click the Donate now link you're simply taken to https://icecoder.net/?display=trialDonateScreen ...that's it. Here's the code:

```
<a href="https://icecoder.net/?display=trialDonateScreen" target="_blank" style="background: #097695; color: #fff; padding: 10px; text-decoration: none; font-size: 17px; font-weight: bold; border-radius: 4px; cursor: pointer">Donate now</a>
```

As you can see, we don't do anything strange, hidden or misleading, (we've absolutely no reason to) and this is an open source project so you can check any of the check within. You'll find there's no beacon-ware or gaining access to your system at all from our point of view. It sounds like your server provider has a false positive here for whatever reason?

The error you mentioned in error-log.txt is a minor item we can look at but not related to any of your concerns above.

Hope that puts your mind at ease and I'll close this issue.
