### ISSUE TITLE
While saving occurs '500 Internal Server Error'

### ISSUE THREAD

**Issue by PhilippMiller** [mattpass/ICEcoder#678]
Hey, I using ICEcoder v5.7 on  a Windows Server with Plesk.

Everytime I hit Ctrl+S to save a file an '500 Internal Server Error' occured.
My dev tool console show me this:

> http://********URL********/gwe/lib/file-control-xhr.php?action=save&fileMDT=1481846633&fileVersion=6&saveType=save&csrf=4dff5cf814fb1b9951dcea59e16ebd2e

Any idea how I can solve this issue?
(I've read the README and installed it just fine with all permissions.)

Permission overwiev:
![image](https://cloud.githubusercontent.com/assets/15052061/21247096/4db8f44a-c32d-11e6-8626-89d7d6504b7d.png)

Console output after try to save:
![image](https://cloud.githubusercontent.com/assets/15052061/21247138/846e710e-c32d-11e6-9214-5d5a3e98af9d.png)

**Comment by mattpass** [comment]
@PhilippMiller Did you ever resolve this issue?

**Comment by PhilippMiller** [comment]
@mattpass No I never done so.
I decided to host this on a linux system (Ubuntu).

There it works just fine for me.
