### ISSUE TITLE
Undefined function utf8_d

### ISSUE THREAD

**Issue by aggsol** [mattpass/ICEcoder#683]
* Ubuntu 16.04.02 LTS
* Apache/2.4.18
* PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )

Right after installation and first start.
```
error-log.txt
[15-Feb-2017 10:01:07 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_dec
ode() in /home/chef/public_html/ICEcoder/lib/settings-common.php:198
Stack trace:
#0 /home/chef/public_html/ICEcoder/lib/file-control.php(108): toUTF8noBOM('\n<!DOCTYPE html...', true)
#1 {main}
  thrown in /home/chef/public_html/ICEcoder/lib/settings-common.php on line 198
[15-Feb-2017 10:01:42 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_dec
ode() in /home/chef/public_html/ICEcoder/lib/settings-common.php:198
Stack trace:
#0 /home/chef/public_html/ICEcoder/lib/file-control.php(108): toUTF8noBOM('\n<!DOCTYPE html...', true)
#1 {main}
  thrown in /home/chef/public_html/ICEcoder/lib/settings-common.php on line 198
```

**Comment by mattpass** [comment]
@aggsol - never come across this issue before. utf8_decode is part of PHP 5 and 7 so should exist as a function for you: http://php.net/manual/en/function.utf8-decode.php

**Comment by mattpass** [comment]
@aggsol - looking at the settings-common.php file - has the utf8_decode function broken onto 2 lines according to your error output. It also complains about it being at line 198 and utf8_decode appears at line 205, so something is wrong with the file you have:

https://github.com/mattpass/ICEcoder/blob/master/lib/settings-common.php#L205

I'd suggest downloading it again and starting afresh.

**Comment by mattpass** [comment]
Going to close this issue, let me know if any more of the same issue.
