### ISSUE TITLE
typescript support please 

### ISSUE THREAD

**Issue by Dj-jom2x** [mattpass/ICEcoder#694]
typescript support please

**Comment by mattpass** [comment]
There's no TypeScript as it's not a mode that exists yet in CodeMirror (the core editing component in ICEcoder).

See here: http://codemirror.net/mode/index.html

If someone were to add a TypeScript mode to CodeMirror, I'd happily include it in a future ICEcoder release.

**Comment by Dj-jom2x** [comment]
yup all i can do for now is to add 

: fileExt == "ts"			? "text/typescript"

on lib/language-modes-partial.js so i my typescript have colors in it ...

but theres no autocomplete or codeassist on it .. mode for it .. .. waiting for this feature 👍

**Comment by mattpass** [comment]
Ha, how about that. Did not spot that JS mode also includes TypeScript if we set the flag for it:

http://codemirror.net/mode/javascript/index.html

Good spot and I'll add this in properly soon (incl icon for .ts files etc)

**Comment by mattpass** [comment]
OK, added TypeScript properly as a language now (so has icon, .ts file is recognised etc). It doesn't really have autocomplete as yet, but I'm aiming to implement autocomplete for any language via devdocs.io. To be done soon!

**Comment by Dj-jom2x** [comment]
thanks
