### ISSUE TITLE
CSRF issue after terminal

### ISSUE THREAD

**Issue by digitart** [mattpass/ICEcoder#697]
A few seconds after opening terminal, I can no longer do anything. Commands are not sended and CLOSE button on terminal do not respond. If I try to go again to the dashboard reloading or opening a new window and writing the URL server hangs and my browser keeps trying to connect to ICEcoder for minutes.
After several minutes I finally get the login screen, but after logging in I get only this report:

CSRF issue:
REQUEST: 72595ebce7b4636c982f5517d2060cd8
SESSION: a8f53199bfba059ad60dcbe885b8dbf8
FILE: /lib/login.php
GET: array ( )
POST: array ( 'username' => 'xxxxx', 'password' => 'xxxxxx', 'submit' => 'login', 'checkUpdates' => 'true', 'csrf' => '72595ebce7b4636c982f5517d2060cd8', )

And nothing else. I have to clean up all the cookies on my browser and login again to be able to see my dashboard again.

**Comment by mattpass** [comment]
@digitart Someone else had a similar issue and ended up with an exhaustion of child processes available, effectively self-dos'ing if proc_open not enabled.

You could try pulling latest commit (https://github.com/mattpass/ICEcoder/commit/c6dc329ab683cb14685052afef6bd0b15365f494), which now checks if it's enabled, else could just check it's enabled on your server.

(There may be a chain of error events happening here - exhausting child processes, dos'ing yourself, causing error 500 and then CSRF errors, which cause a JS error and so even closing the terminal won't work or viewing a page on your site).

**Comment by mattpass** [comment]
I think this was the issue and the commit mentioned now fixes it. Please re-open if not.
