### ISSUE TITLE
File Merges on file save instead of overwriting the file.

### ISSUE THREAD

**Issue by Cass0wary** [mattpass/ICEcoder#698]
icecoder version 6.0
Ubuntu 14.04.5 LTS Trusty
Google chrome Version 57.0.2987.133 (64-bit)

I have a php file, and when I update a line, it will merge that line with the existing document. So when I close the file and reopen it the same line is there twice. The original and the one with the changes. 

I have double checked the file permissions and can confirm that www-data has been tested with 757 and 755.

Is there something that I have changed in icecoder to have caused this to occur?

Cheers, 
J

**Comment by mattpass** [comment]
This was a known issue that's been fixed in commits since the v6.0 beta release. If you get the latest version from this repo, the issue should be resolved.

Please reopen if further issues.
