### ISSUE TITLE
Pricing/Licensing

### ISSUE THREAD

**Issue by dgramop** [mattpass/ICEcoder#701]
Your license does not allow you to enforce your pricing. People can still copy it and sell it as their own. And if you change the license, then it will only apply to later versions of the software.

That means that you are, along with the rest of the world, allowed to sell this software (for the 10$ or whatever you are selling it for), but you can't prevent people from using this code without paying you (at least with the current license)

**Comment by mattpass** [comment]
It's true and something we're not overly concerned about. We chose this license type as we're quite happy for people to take it, modify and sell if they'd like. Wanted to make something awesome first, put it out there as open source and only casually draw in money.

Think I'll have to close this issue as we're at the place we want to be with things. :-)
