### ISSUE TITLE
search and replace

### ISSUE THREAD

**Issue by gkzsolt** [mattpass/ICEcoder#703]
Hi,
I am using ICEcoder for a few days and I find it a very good IDE. It is my first only-browser editor and as such I think it is great. There are only a few things I could not find. 

Where is the search and replace function? 

Is there a keyboard shortcut for moving to the next/previous tab? The shortcuts panel shows Ctrl + left/right arrow, but these work only in "tab" mode. When inside an editor, they just take you to the next word.

Thank you,

**Comment by mattpass** [comment]
I think we covered this on Facebook now, but to recap...

The search and replace is doing by making up a sentence using the textboxes and dropdown options. 

Yes, CTRL+left and CTRL+right will cycle through the tabs when your cursor is not on the editor. CTRL+mouse wheel will also cycle left and right wherever your cursor is.

**Comment by marcoczen** [comment]
You have the Facebook link ? I couldnt find it at https://www.facebook.com/ICEcoder.net.
I dont mind editing the manual so that its mentioned how to do a find+replace.
Right now I use kwrite or kate to to do that outside of icecoder.

**Comment by gkzsolt** [comment]
Unfortunately CTRL+mouse wheel does not help on a Chromebook/laptop. Also, I am used to cycle through the tabs during editing. Tab cycling shortcuts are so often, they are provided by all web browsers even in several variants. E.g. Ctrl [Shift] Tab, or Ctrl 1, 2, ..9.

**Comment by marcoczen** [comment]
You know how Find and replace works ? I can only do a find , not a replace ...

**Comment by gkzsolt** [comment]
After find, open the 'in' dropdown, which offers an 'and replace' option (you'll see only 'and' in the dropdown). I think this should be written/explained somewhere, as some people (me included) see the dropdown, but still don't associate 'and' with 'replace'. (It can be find A and B, for example...)

**Comment by mattpass** [comment]
It was a good suggestion putting info re this in the manual, so I've started a FAQ section and detailed this question here: https://icecoder.net/manual#faq-find-replace
