### ISSUE TITLE
500 Internal Server Error on file opening

### ISSUE THREAD

**Issue by demolitions** [mattpass/ICEcoder#707]
Just tried cloning current GIT master ( a5432a68545bb1905d53da5e71a4a350fe126c16 ) on my laptop, and every file I try to open results in a `HTTP 500` from `file-control.php`. 
Since I don't have this issue on my server, and the only change between server and laptop is the PHP version, I may be inclined to mark a PHP 7.1.5 incompatibility as the root cause.
I'm currently debugging where `file-control.php` stops precisely, more info will follow.

**Comment by demolitions** [comment]
Ok, this is definitely a misconfiguration or another kind of problem on MY end.
Downgraded PHP to 7.0.14 (same version that on my server works without issues), same problem.
The issue is that the PHP process dies without an error (not in apache's error_log, nor in output with `display-errors` set to on) in `settings-common.php` at row 206:
`$teststringConverted = iconv("UTF-8", "UTF-8//IGNORE", $teststringBroken);`

I use almost regularly iconv on my projects and I never happened to come across this issue.
The weird thing is that this happens even on simple plain-text files (no symbols other than ASCII standard ones).

**Comment by demolitions** [comment]
Ok, found the cuplrit.
On my (default) installation, the iconv extension in PHP was not enabled, it's corrected by uncommenting the correct extension row in `php.ini`.
Maybe a note in the requirements would be nice, but I doubt many distros ship PHP without iconv enabled, so again, maybe this is not necessary.
Sorry to bother you, will close this.

**Comment by mattpass** [comment]
No problems, just contemplating if iconv it should be part of the /settings.php checks it performs to ensure you have all that you need to run. It may not be common to have it disabled, but could be useful to check for it and inform users if it is.
