### ISSUE TITLE
License Inquiry - Some Questions

### ISSUE THREAD

**Issue by marcoczen** [mattpass/ICEcoder#709]
Hi , I would like to purchase a license for ice coder and have the following questions;

a. Is icecoder limited to only editing files in the root directory ? I have a subfolder called classes and cannot seem to open any file in them - example, say a file,  test.php . 
Apache error log shows an fopen error -  icecoder is trying to open /webroot/test.php instead of /webroot/classes/test.php.  IceCoder seems to have missed the classes subfolder.

b. Can icecoder only work with 20 files ? I noticed that i couldnt save files when when i had 21 files in the root. Note i was using icecoder 5 - free version

c. Does icecoder have a bracket matching feature ? I click on an open curly brace and it shows me the closing curling brace? Likewise for html elements tags as well.

d. Once the license is  received  ( by email yes ? )  where do we apply it ? I dont see anything in the Edit->Settings area to apply the license

Great Job IceCoder Team !

**Comment by mattpass** [comment]
@marcoczen This isn't really the place to ask general questions, it's more for reporting bugs and helping develop the codebase. I'll answer questions tho and close this issue:

a. No, you can edit files outside of the root dir. It would almost certainly be a .htaccess redirect rule or something else on your server affecting the paths/redirecting.

b. No, you can work when there's 1000's of files in a dir, no issues. Maybe an issue with an older version of ICEcoder and we'd recommend using the latest version.

c. Yes, it does have bracket matching, that was after v5 so again would recommend getting the newer version. It doesn't have tag matching, but does have code folding in the gutter.

d. Yes, once you have a licence unlock code, you can either wait for the 14 day trial to expire and then it'll pompt you to enter it. else, open ICEcoder and ensure you have no files open in it. The dashboard info screen that displays will indicate how many days you have left on your trial and a link to show the screen where you can enter the unlock code. It's a good suggestion to put the license input within Edit->Settings, we'll note that request!

If any further questions, feel free to email at info@icecoder.net

**Comment by marcoczen** [comment]
Thanks.
