### ISSUE TITLE
Is there Find + Replace in Icecoder?

### ISSUE THREAD

**Issue by marcoczen** [mattpass/ICEcoder#712]
In v6.0 Beta, is there a find+replace ?

**Comment by mattpass** [comment]
It's been there for many versions now. Use the dropdowns and textboxes to make up a sentence re what you want to do.

ie, try changing the 'in' option to 'and' to see more options and make up your sentence.

**Comment by marcoczen** [comment]
Ahuh .. Thanks. 
Changing "in" to "and" reveals the replace option. Its right at the top of the edit window, below the tabs.
Can we input this info into the manual ?

**Comment by mattpass** [comment]
Yup, have put this into the manual under a new FAQ section now, good suggestion :-)
