### ISSUE TITLE
IceCoder adds unwanted html tags

### ISSUE THREAD

**Issue by marcoczen** [mattpass/ICEcoder#714]
I have at least several times had code break because icecoder adds tags such as html or body or divs on its own. Happens on both a linux box and a windows box. This is the only serious downside of Icecoder so far. Other than that its a decent ide.
What can we do to stop this  unnecessary tags.

**Comment by mattpass** [comment]
Without reproducing the issue myself I'm unsure if it's CodeMirror (the code editing component in ICEcoder) that's causing this, or some ICEcoder written JS code layered ontop that's causing this issue.

It's best inititally to go to Edit -> Settings -> Style (tab) and change 'auto close tags' from yes to no. That will change the CodeMirror parameter re that. If that doesn't solve your problem, let me know exact steps you're taking please so I can take the exact same steps, reproduce and find any issues. :-)

**Comment by marcoczen** [comment]
I have set 'auto close tags' from yes to no.  Thanks Matt.
Best IDE support ! Nobody comes close !

**Comment by mattpass** [comment]
Awww, you're too kind. Let me know if that doesn't help (and if so, exact steps you take so I can reproduce), else I'll close this issue.

**Comment by marcoczen** [comment]
Update - issue SOLVED by using the 6.0 beta for the repo here.
