### ISSUE TITLE
Code in IceCoder does not match View Source - Though Saved ( No red indicator on tab or * )

### ISSUE THREAD

**Issue by marcoczen** [mattpass/ICEcoder#715]
Code in IceCoder Edit window;

```
<?php

echo "Login_Check";

?>
```

Code in Browser View Source;
```

<?phpEcho "Login_Check";

echo "Login_Check";

```

Note that this could be relevant to the earlier issue i reported  #714 whereby unwanted tags were added.

**Comment by marcoczen** [comment]
Echo "Login_Check"; was something i wrote earlier but i edited it to 
echo "Login_Check";

And saved to execute in the browser.

**Comment by marcoczen** [comment]
Interesting note .. in Chrome 59, it shows;

`<?phpEcho "Login_Check";

echo "Login_Check";`

**Comment by mattpass** [comment]
Have you got the latest version from this GitHub repo? v6.0 beta from the website is slightly older and includes a bug re line endings. If so, grabbing the latest version from GitHub may resolve this issue.

**Comment by marcoczen** [comment]
Will try ... will i have to re-apply the license ?

**Comment by mattpass** [comment]
If you reinstall a copy from GitHub then yes. Future updates to official releases will carry your user configs and therefore licence code over, but a fresh install means you need to unlock the trial again.

**Comment by mattpass** [comment]
Think this issue can be attributed to the v6 beta release and not in this repo since the fix, so closing.

**Comment by marcoczen** [comment]
Issue SOLVED - reinstalled icecoder from this repo. Copied out the license files and overwrote the files after installation.
