### ISSUE TITLE
ICEcoder doesn't load due to permission error, but permissions appear to be ok.

### ISSUE THREAD

**Issue by abalter** [mattpass/ICEcoder#719]
I put ice in a web accessible folder. Permissions are set recursively to 755. When I navigate to the url I get a 500 error. If I replace the index.php with a simple phpinfo() command, that loads just fine. I'm very confused.

Apache error log:

```
[Tue Aug 08 14:09:32.502862 2017] [:error] [pid 27122] [client 192.168.1.10:62307] PHP Warning:  session_regenerate_id(): open(/var/www/html/ice/lib/../tmp/sess_-RUSRbMZNPLVuDV8N7RRJB,dbz9tU1AUgFq-IJL4sL3xObCXllTQ0kdmaU42lVZzM7WCZpl0FnkEFKIllyzxM3, O_RDWR) failed: Permission denied (13) in /var/www/html/ice/lib/settings-common.php on line 38
[Tue Aug 08 14:09:32.502973 2017] [:error] [pid 27122] [client 192.168.1.10:62307] PHP Catchable fatal error:  session_regenerate_id(): Failed to create(read) session ID: files (path: /var/www/html/ice/lib/../tmp) in /var/www/html/ice/lib/settings-common.php on line 38
```

These are the permission on the file it failed to read:

```
-rwxrwxr-x  1 balter www  10572 Aug 25  2016 settings-common.php
```

Here is the offending line:

```
36         @session_start();                                               // Finally, start the session!
37         if (!isset($_SESSION['csrf'])){
38                 session_regenerate_id(true);                            // Create a new ID to help prevent fixation
39         }


```

**Comment by mattpass** [comment]
I would check that you have write permissions on the /tmp dir in ICEcoder, since that's where it's storing session files. When regenerating, it will likely create a new session file in that dir, so needs to be able to do so and so maybe /tmp doesn't quite have the right write permissions. Either that, or the current session file doesn't have enough read permissions to read the data to put into a new session file.

You may be able to get away with just comment out that ```session_regenerate_id(true);``` line, however, it's a good thing to have to avoid session fixation vulnerabilities so I'd avoid doing that.

A better solution for you may be to comment out line 31 in that file re the session save path being in /tmp:
https://github.com/mattpass/ICEcoder/blob/master/lib/settings-common.php#L31

By commenting out that file, session files will them be stored in your server in a more typical place rather than the /tmp path ICEcoder is specifying on that line. That then may resolve your issue.

**Comment by abalter** [comment]
Hi Matt,

I set the entire directory to 775 recursively just to see if that would help, but no dice.

```
balter@homedevbox:/var/www/html/ice$ la -al
total 124
drwxrwxr-x 12 balter www  4096 Aug  8 13:58 .
drwxrwxr-x  5 root   www  4096 Aug  8 13:41 ..
drwxrwxr-x  2 balter www  4096 Jul 29  2016 backups
drwxrwxr-x  5 balter www  4096 Aug 26  2016 CodeMirror
-rwxrwxr-x  1 balter www 17913 Aug 14  2016 editor.php
drwxrwxr-x  2 balter www  4096 Aug 26  2016 farbtastic
-rwxrwxr-x  1 balter www  1331 Apr  2  2016 favicon.png
-rwxrwxr-x  1 balter www  4377 Apr  5  2016 files.php
-rwxrwxr-x  1 balter www   133 Apr  2  2016 .gitignore
drwxrwxr-x  2 balter www  4096 Aug 26  2016 images
-rwxrwxr-x  1 balter www 23935 Aug  8 13:52 index.php
-rw-rw-r--  1 balter www    21 Aug  8 13:45 info.php
drwxrwxr-x  2 balter www  4096 Aug 26  2016 lang
drwxrwxr-x  2 balter www  4096 Aug  8 14:11 lib
-rwxrwxr-x  1 balter www  1441 Apr  2  2016 LICENSE.md
drwxrwxr-x  2 balter www  4096 Aug 26  2016 plugins
drwxrwxr-x  2 balter www  4096 Aug 26  2016 processes
-rwxrwxr-x  1 balter www  1914 Aug 26  2016 README.md
drwxrwxr-x  2 balter www  4096 Aug 26  2016 test
-rwxrwxr-x  1 balter www  3531 Apr  2  2016 test.php
drwxrwxr-x  2 balter www  4096 Aug 26  2016 tmp
```

And I commented out the line:

```
balter@homedevbox:/var/www/html/ice/lib$ head -35 settings-common.php | tail -10
        ini_set('session.use_trans_sid','0');                           // Ensure this insecure feature is disabled
        ini_set('session.hash_function','sha512');                      // Use Sha512 for session
        ini_set('session.hash_bits_per_character','6');                 // Specify hash scheme of 0-9,a-v,A-Z,-,,
//      ini_set('session.use_strict_mode','1');                         // Reject any session ID that was user provided and not generated by the session                        (since PHP 5.5.2)
        ini_set('session.httponly','1');                                // Only allow http protocol (ie, not JS) access to the cookie                                           (since PHP 5.2.0)
        //ini_set('session.save_path',dirname(__FILE__).'/../tmp');     // Localise the session files to /tmp

        if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
                ini_set('session.cookie_secure','1');                   // Only allows access to session ID when protocol is HTTPS, switched on under 'if https' condition
        }
```

Now I get this: "Cannot update config file lib/config___settings.php. Please check write permissions on lib/ and try again"

I just don't see how I could have a permissions error!

**Comment by abalter** [comment]
Well, I tried setting permissions recursively to 777 and now it works. So somehow root doesn't have access except as "other." That is very odd.

**Comment by abalter** [comment]
Ok, here's what I did to fix it. I realized that I didn't have group set to `www-data` for everything. I fixed that, and pulled back permissions to 775. Now all works well.

**Comment by mattpass** [comment]
Ah good, so just a server and permissions thing. Guess this can be closed then, pls reopen if any code amends need to be made, but sounds like server/perms you side. :-)

**Comment by seyo-IV** [comment]
Hi there i have a similar issue. After the initial setup, i have reloaded the page and now im only getting 403 Forbidden. I have already triyed to set differenct write permissions but it didnt help.
