### ISSUE TITLE
Couldn't establish version, probably couldn't include settings file!

### ISSUE THREAD

**Issue by mayaankvad** [mattpass/ICEcoder#722]
I have a lamp stack and am trying to run ICEcoder.
I go to ICEcoder and immediately get hit with a 500 error.

When i go to tests.php the following item (test 3) is in red:

Couldn't establish version, probably couldn't include settings file!

How do I fix this. I am using v5.0 right now because it is free.

**Comment by mattpass** [comment]
It may be that you don't have fopen enabled on your server.

**Comment by mayaankvad** [comment]
It is enabled. Another app I have runs fine and it also requires fopen

**Comment by mayaankvad** [comment]
Fixed. 
I ran chmod -R 777 on the directory and it worked

**Comment by mattpass** [comment]
Cool, glad you sorted it out. It almost always tends to be a server related thing. :-) Will close this issue.

**Comment by MohitDeshwal** [comment]
same issue, chmod din't help.

**Comment by MohitDeshwal** [comment]
@mayaankvad i turned on errors and tried.
turnes out, zip extension for php was required.
please disclose it to users for future.
